package codegen

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAnalyzeDiscoversBaselineModel(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go":                   "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct { Enabled bool }\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\", Middlewares: []module.ComponentRef{module.Ref(\"middleware.New\")}, GlobalMiddlewares: []module.ComponentRef{module.Ref(\"middleware/global.NewTrace\")}} }\n",
		"modules/demo/middleware/middleware.go":    "package middleware\ntype Service struct{}\nfunc New() *Service { return &Service{} }\n",
		"modules/demo/middleware/global/global.go": "package global\ntype Trace struct{}\nfunc NewTrace() *Trace { return &Trace{} }\n",
		"modules/demo/service/service.go":          "package service\ntype Worker struct{}\nfunc NewWorker() (*Worker, error) { return &Worker{}, nil }\n",
		"modules/demo/service/generated_gen.go":    "// Code generated by test. DO NOT EDIT.\npackage service\nfunc NewGenerated() *Worker { return &Worker{} }\n",
		"modules/demo/service/worker_test.go":      "package service\nfunc NewTest() *Worker { return &Worker{} }\n",
	})
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	modules := model.Modules()
	if len(modules) != 1 || modules[0].Identity().Key() != "demo" {
		t.Fatalf("Modules() = %#v", modules)
	}
	if modules[0].Config().TypeName() != "Config" || len(modules[0].References()) != 2 {
		t.Fatalf("module = %#v", modules[0])
	}
	constructors := modules[0].Constructors()
	if len(constructors) != 3 || constructors[2].Name() != "NewWorker" {
		t.Fatalf("Constructors() = %#v", constructors)
	}
}

func TestAnalyzeReportsInvalidConstructor(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go":          "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/service/service.go": "package service\ntype Worker struct{}\nfunc NewWorker() Worker { return Worker{} }\n",
	})
	_, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	var diagnostics *DiagnosticError
	if !errors.As(err, &diagnostics) {
		t.Fatalf("Analyze() error = %v, want DiagnosticError", err)
	}
	if len(diagnostics.Diagnostics()) != 1 || diagnostics.Diagnostics()[0].Code != "CG022" {
		t.Fatalf("Diagnostics() = %#v", diagnostics.Diagnostics())
	}
}

func TestAnalyzeDiscoversLifecycleInterfacesByExactSignature(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go": "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/service/service.go": `package service

import "context"

type Worker struct{}
type Similar struct{}

func NewWorker() *Worker { return &Worker{} }
func NewSimilar() *Similar { return &Similar{} }
func (*Worker) OnInit(context.Context) error { return nil }
func (*Worker) OnStart(context.Context) error { return nil }
func (*Worker) OnStop(context.Context) error { return nil }
func (*Similar) OnInit(string) error { return nil }
`,
	})
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatal(err)
	}
	constructors := model.Modules()[0].Constructors()
	if len(constructors) != 2 {
		t.Fatalf("Constructors() = %#v", constructors)
	}
	var worker, similar Constructor
	for _, constructor := range constructors {
		switch constructor.Name() {
		case "NewWorker":
			worker = constructor
		case "NewSimilar":
			similar = constructor
		}
	}
	if !worker.HasInitializer() || !worker.HasStarter() || !worker.HasStopper() {
		t.Fatalf("worker lifecycle = %#v", worker)
	}
	if similar.HasInitializer() || similar.HasStarter() || similar.HasStopper() {
		t.Fatalf("similar lifecycle = %#v", similar)
	}
}

func TestAnalyzeDiscoversTransportByExactSignature(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go": "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/service/server.go": `package service

import "context"

type Server struct{}
type Similar struct{}

func NewServer() *Server { return &Server{} }
func NewSimilar() *Similar { return &Similar{} }
func (*Server) Name() string { return "http" }
func (*Server) Prepare(context.Context) error { return nil }
func (*Server) Start(context.Context) (<-chan error, error) { return make(chan error), nil }
func (*Server) Stop(context.Context) error { return nil }
func (*Similar) Name() string { return "grpc" }
func (*Similar) Prepare(context.Context) error { return nil }
func (*Similar) Start(context.Context) (chan<- error, error) { return make(chan error), nil }
func (*Similar) Stop(context.Context) error { return nil }
`,
	})
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatal(err)
	}
	constructors := model.Modules()[0].Constructors()
	if len(constructors) != 2 {
		t.Fatalf("Constructors() = %#v", constructors)
	}
	for _, constructor := range constructors {
		switch constructor.Name() {
		case "NewServer":
			if !constructor.HasTransport() {
				t.Fatal("NewServer transport = false")
			}
		case "NewSimilar":
			if constructor.HasTransport() {
				t.Fatal("NewSimilar transport = true")
			}
		}
	}
}

func TestAnalyzeDiscoversOutboxRolesByExactSignature(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go": "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/service/outbox.go": `package service

import (
	"context"

	"github.com/toothdy/cool-admin-go-next/cool-next/outbox"
)

type Producer struct{}
type Publisher struct{}
type Adapter struct{}

func NewProducer(outbox.Enqueuer) *Producer { return &Producer{} }
func NewPublisher() *Publisher { return &Publisher{} }
func NewAdapter() *Adapter { return &Adapter{} }
func (*Publisher) Publish(context.Context, outbox.Envelope) error { return nil }
func (*Adapter) Name() string { return "broker" }
func (*Adapter) Capabilities(context.Context) (outbox.ConsumerCapabilities, error) {
	return outbox.ConsumerCapabilities{}, nil
}
func (*Adapter) Prepare(context.Context, []outbox.Subscription, outbox.DeliverFunc) error { return nil }
func (*Adapter) Start(context.Context) (<-chan error, error) { return make(chan error), nil }
func (*Adapter) Stop(context.Context) error { return nil }
`,
		"modules/demo/consumer/created.go": `package consumer

import (
	"context"

	"github.com/toothdy/cool-admin-go-next/cool-next/outbox"
)

type Payload struct { ID uint64 }

func NewCreated() (outbox.ConsumerDefinition, error) {
	return outbox.Consume("demo-created", "demo.created", "demo.Created", []uint32{1}, func(context.Context, outbox.Incoming[Payload]) error { return nil })
}
`,
	})
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatal(err)
	}
	roles := make(map[string]Constructor)
	for _, constructor := range model.Modules()[0].Constructors() {
		roles[constructor.name] = constructor
	}
	if !roles["NewProducer"].isProducer || roles["NewProducer"].isPublisher || roles["NewProducer"].isConsumerAdapter {
		t.Fatalf("NewProducer roles = %#v", roles["NewProducer"])
	}
	if !roles["NewPublisher"].isPublisher || !roles["NewAdapter"].isConsumerAdapter {
		t.Fatalf("infrastructure roles = %#v %#v", roles["NewPublisher"], roles["NewAdapter"])
	}
	if !roles["NewCreated"].isConsumerDefinition || roles["NewCreated"].hasStarter || roles["NewCreated"].hasStopper {
		t.Fatalf("NewCreated roles = %#v", roles["NewCreated"])
	}
	created := roles["NewCreated"]
	if created.consumerName != "demo-created" || created.consumerTopic != "demo.created" ||
		created.consumerMessageType != "demo.Created" || len(created.consumerVersions) != 1 || created.consumerVersions[0] != 1 {
		t.Fatalf("NewCreated metadata = %#v", created)
	}
}

func TestAnalyzeRejectsDynamicOrDuplicateConsumerMetadata(t *testing.T) {
	tests := []struct {
		name    string
		files   map[string]string
		code    string
		message string
	}{
		{
			name: "dynamic metadata",
			files: map[string]string{
				"modules/demo/config.go":           "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
				"modules/demo/consumer/created.go": "package consumer\nimport (\"context\"; \"github.com/toothdy/cool-admin-go-next/cool-next/outbox\")\ntype Payload struct{}\nfunc NewCreated() (outbox.ConsumerDefinition, error) { name := \"demo-created\"; return outbox.Consume(name, \"demo.created\", \"demo.Created\", []uint32{1}, func(context.Context, outbox.Incoming[Payload]) error { return nil }) }\n",
			},
			code:    "CG105",
			message: "生成期常量",
		},
		{
			name: "duplicate name",
			files: map[string]string{
				"modules/demo/config.go":          "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
				"modules/demo/consumer/first.go":  "package consumer\nimport (\"context\"; \"github.com/toothdy/cool-admin-go-next/cool-next/outbox\")\ntype First struct{}\nfunc NewFirst() (outbox.ConsumerDefinition, error) { return outbox.Consume(\"same-name\", \"demo.first\", \"demo.First\", []uint32{1}, func(context.Context, outbox.Incoming[First]) error { return nil }) }\n",
				"modules/demo/consumer/second.go": "package consumer\nimport (\"context\"; \"github.com/toothdy/cool-admin-go-next/cool-next/outbox\")\ntype Second struct{}\nfunc NewSecond() (outbox.ConsumerDefinition, error) { return outbox.Consume(\"same-name\", \"demo.second\", \"demo.Second\", []uint32{1}, func(context.Context, outbox.Incoming[Second]) error { return nil }) }\n",
			},
			code:    "CG106",
			message: "全局重复",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeWorkspace(t, test.files)
			_, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
			var diagnostics *DiagnosticError
			if !errors.As(err, &diagnostics) || len(diagnostics.Diagnostics()) != 1 ||
				diagnostics.Diagnostics()[0].Code != test.code ||
				!strings.Contains(diagnostics.Diagnostics()[0].Message, test.message) {
				t.Fatalf("Analyze() error = %v", err)
			}
		})
	}
}

func TestAnalyzeClassifiesServiceActionsAndHooks(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go":         "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/dto/product.go":    "package dto\ntype PageReq struct { Page int }\ntype PageResult struct { Total int }\n",
		"modules/demo/entity/product.go": "package entity\ntype Product struct{}\n",
		"modules/demo/service/product.go": `package service
import (
	"context"
	coreservice "github.com/toothdy/cool-admin-go-next/cool-next/core/service"
	"example.test/app/modules/demo/dto"
	"example.test/app/modules/demo/entity"
)
type ProductService struct { *coreservice.Base[entity.Product, uint64] }
func (service *ProductService) Add(ctx context.Context, input coreservice.AddInput[entity.Product]) (coreservice.AddResult[uint64], error) {
	return service.Base.Add(ctx, input)
}
func (service *ProductService) Delete(ctx context.Context, input coreservice.DeleteInput[uint64]) error {
	return service.delete(ctx, input)
}
func (service *ProductService) delete(ctx context.Context, input coreservice.DeleteInput[uint64]) error {
	return service.Base.Delete(ctx, input)
}
func (service *ProductService) Update(ctx context.Context, input coreservice.UpdateInput[entity.Product, uint64]) error {
	if input.IsMany() { return service.Base.Update(ctx, input) }
	return nil
}
func (*ProductService) Info(context.Context, uint64) (map[string]string, error) {
	return map[string]string{"name": "product"}, nil
}
func (*ProductService) List(context.Context, coreservice.Query) ([]string, error) {
	return []string{"product"}, nil
}
func (*ProductService) Page(context.Context, *dto.PageReq) (dto.PageResult, error) {
	return dto.PageResult{Total: 1}, nil
}
func (service *ProductService) ModifyBefore(context.Context, *coreservice.Mutation[entity.Product, uint64]) error {
	return nil
}
`,
	})
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatal(err)
	}
	services := model.Modules()[0].Services()
	if len(services) != 1 || services[0].Name() != "ProductService" || !services[0].HasModifyBefore() || services[0].HasModifyAfter() {
		t.Fatalf("Services() = %#v", services)
	}
	want := map[string]ServiceActionMode{
		"Add":    ServiceActionDelegate,
		"Delete": ServiceActionOverride,
		"Update": ServiceActionDelegate,
		"Info":   ServiceActionOverride,
		"List":   ServiceActionOverride,
		"Page":   ServiceActionOverride,
	}
	for _, action := range services[0].Actions() {
		if action.Mode() != want[action.Name()] {
			t.Fatalf("action %s mode = %s, want %s", action.Name(), action.Mode(), want[action.Name()])
		}
	}
}

func TestAnalyzeIgnoresConfigFilesInsideModuleSourceDirectories(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go":                "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/service/config.go":        "package service\ntype Settings struct { Timeout int }\nfunc NewSettings() *Settings { return &Settings{} }\n",
		"modules/system/user/config.go":         "package user\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"User\", Description: \"User module\"} }\n",
		"modules/system/user/service/config.go": "package service\ntype Settings struct { Timeout int }\nfunc NewSettings() *Settings { return &Settings{} }\n",
	})
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	modules := model.Modules()
	if len(modules) != 2 || modules[0].Identity().Key() != "demo" || modules[1].Identity().Key() != "system/user" {
		t.Fatalf("Modules() = %#v", modules)
	}
	for _, current := range modules {
		constructors := current.Constructors()
		if len(constructors) != 1 || constructors[0].Name() != "NewSettings" {
			t.Fatalf("Constructors() = %#v", constructors)
		}
	}
}

func TestAnalyzeRejectsModuleConfigInsideModuleSourceDirectory(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go":               "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/service/child/config.go": "package child\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Child\", Description: \"Child module\"} }\n",
	})
	_, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	var diagnostics *DiagnosticError
	if !errors.As(err, &diagnostics) {
		t.Fatalf("Analyze() error = %v, want DiagnosticError", err)
	}
	values := diagnostics.Diagnostics()
	if len(values) != 1 || values[0].Code != "CG003" || values[0].Position.File != "modules/demo/service/child/config.go" {
		t.Fatalf("Diagnostics() = %#v", values)
	}
}

func TestAnalyzeRejectsPositionalDeclarationLiteral(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go": "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] {\n\treturn module.Declaration[Config]{\"Demo\", \"Demo module\", 0, nil, nil, Config{}}\n}\n",
	})
	_, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	var diagnostics *DiagnosticError
	if !errors.As(err, &diagnostics) {
		t.Fatalf("Analyze() error = %v, want DiagnosticError", err)
	}
	values := diagnostics.Diagnostics()
	if len(values) != 1 || values[0].Code != "CG012" || values[0].Position.File != "modules/demo/config.go" || values[0].Position.Line != 5 {
		t.Fatalf("Diagnostics() = %#v", values)
	}
}

func TestAnalyzePreservesPackageErrorPosition(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go":         "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
		"modules/demo/service/broken.go": "package service\n\nconst _ = missing\n",
	})
	_, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	var diagnostics *DiagnosticError
	if !errors.As(err, &diagnostics) {
		t.Fatalf("Analyze() error = %v, want DiagnosticError", err)
	}
	values := diagnostics.Diagnostics()
	if len(values) != 1 || values[0].Code != "CG008" || values[0].Position.File != "modules/demo/service/broken.go" || values[0].Position.Line != 3 || values[0].Position.Column != 11 {
		t.Fatalf("Diagnostics() = %#v", values)
	}
}

func TestAnalyzeWithOverlayIgnoresInvalidCommittedOutput(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/modules_gen.go": "package modules\nvar _ = deleted.Symbol\n",
		"modules/demo/config.go": "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
	})
	target := filepath.Join(root, "modules", "modules_gen.go")
	overlay := map[string][]byte{target: []byte("package modules\n")}

	model, err := analyzeOverlay(context.Background(), Options{Dir: root, ModulesRoot: "modules"}, overlay)
	if err != nil {
		t.Fatalf("analyzeWithOverlay() error = %v", err)
	}
	if modules := model.Modules(); len(modules) != 1 || modules[0].Identity().Key() != "demo" {
		t.Fatalf("Modules() = %#v", modules)
	}
	if string(overlay[target]) != "package modules\n" {
		t.Fatalf("overlay = %q", overlay[target])
	}
}

func TestAnalyzeStillReadsCommittedOutput(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/modules_gen.go": "package modules\nvar _ = deleted.Symbol\n",
		"modules/demo/config.go": "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo module\"} }\n",
	})

	_, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err == nil {
		t.Fatal("Analyze() error = nil, want committed output error")
	}
}

func TestCloneOverlayCopiesMapAndBytes(t *testing.T) {
	source := map[string][]byte{"modules/modules_gen.go": []byte("package modules\n")}
	cloned := cloneOverlay(source)

	cloned["modules/modules_gen.go"][0] = 'P'
	cloned["other.go"] = []byte("package other\n")
	if string(source["modules/modules_gen.go"]) != "package modules\n" || len(source) != 1 {
		t.Fatalf("source overlay changed: %#v", source)
	}
}

func TestBuildGraphOrdersComponents(t *testing.T) {
	root := writeWorkspace(t, map[string]string{
		"modules/demo/config.go":          "package demo\nimport module \"github.com/toothdy/cool-admin-go-next/cool-next/core/module\"\ntype Config struct{}\nfunc ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: \"Demo\", Description: \"Demo\"} }\n",
		"modules/demo/service/service.go": "package service\ntype First struct{}\ntype Second struct{}\nfunc NewFirst() *First { return &First{} }\nfunc NewSecond(first *First) *Second { return &Second{} }\n",
	})
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatal(err)
	}
	graph, err := BuildGraph(model)
	if err != nil {
		t.Fatal(err)
	}
	order := graph.Order()
	if len(order) != 2 || order[0].Name() != "NewFirst" || order[1].Name() != "NewSecond" {
		t.Fatalf("Order() = %#v", order)
	}
}

func writeWorkspace(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	moduleRoot, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	moduleFile, err := os.ReadFile(filepath.Join(moduleRoot, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	moduleSum, err := os.ReadFile(filepath.Join(moduleRoot, "go.sum"))
	if err != nil {
		t.Fatal(err)
	}
	moduleContent := strings.Replace(string(moduleFile), "module github.com/toothdy/cool-admin-go-next", "module example.test/app", 1)
	moduleContent += "\nrequire github.com/toothdy/cool-admin-go-next v0.0.0\nreplace github.com/toothdy/cool-admin-go-next => " + moduleRoot + "\n"
	writeTestFile(t, root, "go.mod", moduleContent)
	writeTestFile(t, root, "go.sum", string(moduleSum))
	for name, content := range files {
		writeTestFile(t, root, name, content)
	}
	return root
}

func writeTestFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestAnalyzeDiscoversControllerDeclarations(t *testing.T) {
	files := controllerAnalysisWorkspace()
	files["modules/demo/controller/admin/sys/goods.go"] = `package sys
import (
	"context"
	controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
	coreservice "github.com/toothdy/cool-admin-go-next/cool-next/core/service"
	"example.test/app/modules/demo/entity"
	demoservice "example.test/app/modules/demo/service"
)
func GoodsController(service *demoservice.ProductService) controller.Definition {
	entityValue := entity.Product{}
	insert := controller.Insert[entity.Product](func(context.Context, *coreservice.Mutable[entity.Product]) error { return nil })
	option := controller.CurdOption{
		API: controller.AllAPI(),
		Entity: entityValue,
		Service: service,
		InsertParam: insert,
	}
	return controller.Admin("").Curd(option).Build()
}
`
	files["modules/demo/controller/app/item.go"] = `package app
import (
	controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
	"example.test/app/modules/demo/entity"
	demoservice "example.test/app/modules/demo/service"
)
const route = "public/items"
func ItemController(service *demoservice.ProductService) controller.Definition {
	return controller.App(route).Curd(controller.CurdOption{
		Prefix: "archive/items",
		Entity: entity.Product{},
		Service: service,
	}).Build()
}
`
	files["modules/demo/controller/app/health.go"] = `package app
import controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
func HealthController() controller.Definition { return controller.App("").Build() }
`
	root := writeWorkspace(t, files)
	model, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
	if err != nil {
		t.Fatal(err)
	}
	controllers := model.Modules()[0].Controllers()
	if len(controllers) != 3 {
		t.Fatalf("Controllers() = %#v", controllers)
	}
	values := make(map[string]ControllerDeclaration, len(controllers))
	for _, current := range controllers {
		values[current.Name()] = current
	}
	goods := values["GoodsController"]
	if goods.Area() != ControllerAdmin || goods.Path() != "/admin/demo/sys/goods" || goods.Prefix() != goods.Path() || !goods.HasCurd() {
		t.Fatalf("GoodsController = %#v", goods)
	}
	item := values["ItemController"]
	if item.Area() != ControllerApp || item.Path() != "/app/public/items" || item.Prefix() != "/app/archive/items" || !item.HasCurd() {
		t.Fatalf("ItemController = %#v", item)
	}
	health := values["HealthController"]
	if health.Path() != "/app/demo/health" || health.Prefix() != health.Path() || health.HasCurd() {
		t.Fatalf("HealthController = %#v", health)
	}
	controllers[0].path = "changed"
	if model.Modules()[0].Controllers()[0].Path() == "changed" {
		t.Fatal("Controllers() did not return a copy")
	}
}

func TestAnalyzeReportsControllerDiagnostics(t *testing.T) {
	tests := []struct {
		name       string
		file       string
		controller string
		code       string
	}{
		{
			name: "dynamic factory",
			file: "modules/demo/controller/admin/product.go",
			controller: `package admin
import controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
func ProductController() controller.Definition {
	builder := controller.Admin("")
	return builder.Build()
}
`,
			code: "CG023",
		},
		{
			name: "area mismatch",
			file: "modules/demo/controller/admin/product.go",
			controller: `package admin
import controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
func ProductController() controller.Definition { return controller.App("").Build() }
`,
			code: "CG024",
		},
		{
			name: "duplicate Curd",
			file: "modules/demo/controller/admin/product.go",
			controller: `package admin
import (
	controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
	"example.test/app/modules/demo/entity"
	demoservice "example.test/app/modules/demo/service"
)
func ProductController(service *demoservice.ProductService) controller.Definition {
	option := controller.CurdOption{Entity: entity.Product{}, Service: service}
	return controller.Admin("").Curd(option).Curd(option).Build()
}
`,
			code: "CG025",
		},
		{
			name: "nonzero Entity",
			file: "modules/demo/controller/admin/product.go",
			controller: `package admin
import (
	controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
	"example.test/app/modules/demo/entity"
	demoservice "example.test/app/modules/demo/service"
)
func ProductController(service *demoservice.ProductService) controller.Definition {
	return controller.Admin("").Curd(controller.CurdOption{Entity: entity.Product{Name: "x"}, Service: service}).Build()
}
`,
			code: "CG026",
		},
		{
			name: "Service is not parameter",
			file: "modules/demo/controller/admin/product.go",
			controller: `package admin
import (
	controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
	"example.test/app/modules/demo/entity"
	demoservice "example.test/app/modules/demo/service"
)
func ProductController() controller.Definition {
	return controller.Admin("").Curd(controller.CurdOption{Entity: entity.Product{}, Service: &demoservice.ProductService{}}).Build()
}
`,
			code: "CG027",
		},
		{
			name: "Base Entity mismatch",
			file: "modules/demo/controller/admin/product.go",
			controller: `package admin
import (
	controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
	"example.test/app/modules/demo/entity"
	demoservice "example.test/app/modules/demo/service"
)
func ProductController(service *demoservice.ProductService) controller.Definition {
	return controller.Admin("").Curd(controller.CurdOption{Entity: entity.Other{}, Service: service}).Build()
}
`,
			code: "CG028",
		},
		{
			name: "Insert Entity mismatch",
			file: "modules/demo/controller/admin/product.go",
			controller: `package admin
import (
	"context"
	controller "github.com/toothdy/cool-admin-go-next/cool-next/core/controller"
	coreservice "github.com/toothdy/cool-admin-go-next/cool-next/core/service"
	"example.test/app/modules/demo/entity"
	demoservice "example.test/app/modules/demo/service"
)
func ProductController(service *demoservice.ProductService) controller.Definition {
	return controller.Admin("").Curd(controller.CurdOption{
		Entity: entity.Product{}, Service: service,
		InsertParam: controller.Insert[entity.Other](func(context.Context, *coreservice.Mutable[entity.Other]) error { return nil }),
	}).Build()
}
`,
			code: "CG029",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			files := controllerAnalysisWorkspace()
			files[test.file] = test.controller
			root := writeWorkspace(t, files)
			_, err := Analyze(context.Background(), Options{Dir: root, ModulesRoot: "modules"})
			var diagnostics *DiagnosticError
			if !errors.As(err, &diagnostics) {
				t.Fatalf("Analyze() error = %v", err)
			}
			values := diagnostics.Diagnostics()
			if len(values) != 1 || values[0].Code != test.code || values[0].Position.File != test.file || values[0].Position.Line < 1 || values[0].Position.Column < 1 {
				t.Fatalf("Diagnostics() = %#v", values)
			}
		})
	}
}

func controllerAnalysisWorkspace() map[string]string {
	return map[string]string{
		"modules/demo/config.go": `package demo
import module "github.com/toothdy/cool-admin-go-next/cool-next/core/module"
type Config struct{}
func ModuleConfig() module.Declaration[Config] { return module.Declaration[Config]{Name: "Demo", Description: "Demo module"} }
`,
		"modules/demo/entity/product.go": `package entity
import (
	"github.com/gogf/gf/v2/frame/g"
	coreentity "github.com/toothdy/cool-admin-go-next/cool-next/core/entity"
)
type Product struct {
	g.Meta ` + "`orm:\"table:product\" description:\"Product\"`" + `
	coreentity.Base
	Name string ` + "`json:\"name\" orm:\"name\" description:\"Name\"`" + `
}
type Other struct {
	g.Meta ` + "`orm:\"table:other\" description:\"Other\"`" + `
	coreentity.Base
}
`,
		"modules/demo/service/product.go": `package service
import (
	coreservice "github.com/toothdy/cool-admin-go-next/cool-next/core/service"
	"example.test/app/modules/demo/entity"
)
type ProductService struct { *coreservice.Base[entity.Product, uint64] }
`,
	}
}

func TestAnalyzeValidatesTransientEntityFields(t *testing.T) {
	tests := []struct {
		name      string
		field     string
		index     string
		wantError bool
	}{
		{name: "valid", field: `RoleIDList *[]uint64 ` + "`json:\"roleIdList\" description:\"角色 ID 列表\" cool:\"transient\"`"},
		{name: "orm", field: `RoleIDList *[]uint64 ` + "`json:\"roleIdList\" orm:\"roleIdList\" description:\"角色 ID 列表\" cool:\"transient\"`", wantError: true},
		{name: "index", field: `RoleIDList *[]uint64 ` + "`json:\"roleIdList\" description:\"角色 ID 列表\" cool:\"transient\"`", index: `coreentity.IndexOf("idx_product_role_ids", "roleIdList"),`, wantError: true},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			model := analyzeDescriptorFixture(t, fmt.Sprintf(`
package entity

import (
	coreentity "github.com/toothdy/cool-admin-go-next/cool-next/core/entity"
	"github.com/gogf/gf/v2/frame/g"
)

type Product struct {
	g.Meta `+"`orm:\"table:demo_product\" description:\"商品\"`"+`
	coreentity.Base
	Name string `+"`json:\"name\" orm:\"name\" description:\"名称\"`"+`
	%s
}

func ProductSchema() coreentity.Schema {
	return coreentity.Schema{Indexes: []coreentity.Index{%s}}
}
`, test.field, test.index))
			set, err := CompileDescriptors(model)
			if test.wantError {
				if err == nil {
					t.Fatal("CompileDescriptors() error = nil")
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if declaration := set.Fragments()[0].DODeclaration(); strings.Contains(declaration, "RoleIDList") ||
				strings.Contains(declaration, "roleIdList") {
				t.Fatalf("DODeclaration() contains transient field: %q", declaration)
			}
		})
	}
}
