package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"slices"
	"sort"
	"strconv"
	"strings"

	coreroute "github.com/toothdy/cool-admin-go-next/cool-next/core/route"
)

const generatedFileHeader = "// Code generated by cool. DO NOT EDIT.\n\n"
const authPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/auth"
const authBcryptPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/auth/bcrypt"
const routePackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/core/route"
const appPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/core/app"
const appHTTPPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/core/app/http"
const configurationPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/core/configuration"
const exceptionPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/core/exception"
const epsPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/eps"
const grpcPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/grpc"
const ghttpPackagePath = "github.com/gogf/gf/v2/net/ghttp"
const gmodePackagePath = "github.com/gogf/gf/v2/util/gmode"
const gredisPackagePath = "github.com/gogf/gf/v2/database/gredis"
const outboxStorePackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/outbox/store"
const schemaPackagePath = "github.com/toothdy/cool-admin-go-next/cool-next/db/schema"

// 渲染唯一模块注册表源码
func Render(model *Model, graph *Graph, descriptors *DescriptorSet) ([]byte, error) {
	if model == nil {
		return nil, renderError("CG070", "分析模型不能为空", Position{})
	}
	if graph == nil {
		return nil, renderError("CG071", "Provider 图不能为空", Position{})
	}
	if descriptors == nil {
		return nil, renderError("CG072", "Descriptor 集合不能为空", Position{})
	}
	modules, constructors, err := renderModel(model)
	if err != nil {
		return nil, err
	}
	fragments, err := renderFragments(model, descriptors, modules)
	if err != nil {
		return nil, err
	}
	ordered, err := renderComponents(graph, constructors)
	if err != nil {
		return nil, err
	}
	services := renderServices(model)
	controllers := renderControllers(model)
	registrars := renderGRPCRegistrars(model)
	if err := validateGeneratedIdentifiers(fragments, ordered, services, controllers); err != nil {
		return nil, err
	}
	if err := validateControllerDependencies(controllers, ordered); err != nil {
		return nil, err
	}
	if err := validateHTTPDependencies(modules, fragments, services, controllers, ordered, hasAuthProviders(graph.Providers())); err != nil {
		return nil, err
	}
	providers, descriptorProviders, err := renderProviders(graph, fragments)
	if err != nil {
		return nil, err
	}
	dependencies, err := renderDependencies(graph, ordered, providers)
	if err != nil {
		return nil, err
	}
	if err := validateProviderExpressions(dependencies, modules, fragments, descriptorProviders, ordered); err != nil {
		return nil, err
	}
	imports := newImportManager()
	imports.add(modulePackagePath, "module")
	imports.add(appPackagePath, "app")
	imports.add(appHTTPPackagePath, "apphttp")
	imports.add(configurationPackagePath, "configuration")
	imports.add(exceptionPackagePath, "exception")
	imports.add(grpcPackagePath, "coolgrpc")
	imports.add(grpcxPackagePath, "grpcx")
	imports.add(ghttpPackagePath, "ghttp")
	imports.add(gdbPackagePath, "gdb")
	imports.add(gredisPackagePath, "gredis")
	imports.add(queryPackagePath, "crud")
	imports.add(outboxPackagePath, "outbox")
	for _, current := range modules {
		imports.add(current.config.packagePath, current.config.packageName)
	}
	hasSeed := false
	for _, current := range modules {
		hasSeed = hasSeed || current.seedDB || current.seedMenu
	}
	if hasSeed {
		imports.add("embed", "_")
		imports.add(seedPackagePath, "seed")
	}
	hasOutbox := len(graph.producers) > 0 || len(graph.consumers) > 0
	for _, fragment := range fragments {
		imports.add(entityPackagePath, "coreentity")
		imports.add(servicePackagePath, "coreservice")
		imports.add(gPackagePath, "g")
		imports.add(fragment.entityPackage, fragment.entityQualifier)
	}
	if len(fragments) > 0 || hasOutbox {
		imports.add(entityPackagePath, "coreentity")
		imports.add(databasePackagePath, "coredb")
		imports.add(recyclePackagePath, "corerecycle")
	}
	if len(fragments) > 0 || hasOutbox {
		imports.add(schemaPackagePath, "dbschema")
	}
	if hasOutbox {
		imports.add(outboxStorePackagePath, "outboxstore")
	}
	imports.add("context", "context")
	if len(services) > 0 {
		imports.add(servicePackagePath, "coreservice")
	}
	for _, current := range services {
		imports.add(current.declaration.packagePath, current.declaration.packageName)
		collectTypeImports(imports, current.declaration.entityType)
		collectTypeImports(imports, current.declaration.idType)
	}
	if len(controllers) > 0 {
		imports.add(controllerPackagePath, "corecontroller")
		imports.add(entityPackagePath, "coreentity")
		imports.add(epsPackagePath, "eps")
		imports.add(gmodePackagePath, "gmode")
		imports.add(routePackagePath, "coreroute")
	}
	if hasAuthProviders(graph.Providers()) {
		imports.add(authPackagePath, "auth")
	}
	if hasFrameworkProvider(graph.Providers(), authBcryptPackagePath, "Verifier") {
		imports.add(authBcryptPackagePath, "authbcrypt")
	}
	for _, current := range controllers {
		imports.add(current.declaration.packagePath, current.declaration.packageName)
		for _, parameter := range current.declaration.parameterTypes {
			collectTypeImports(imports, parameter)
		}
		for _, route := range current.declaration.routes {
			if route.handler.HasRequest {
				imports.add(route.handler.RequestPackagePath, "dto")
			}
		}
	}
	if len(ordered) > 0 {
		imports.add(exceptionPackagePath, "exception")
	}
	if len(registrars) > 0 {
		imports.add(exceptionPackagePath, "exception")
	}
	for _, current := range registrars {
		imports.add(current.declaration.packagePath, current.declaration.packageName)
	}
	for _, current := range ordered {
		imports.add(current.constructor.packagePath, current.constructor.packageName)
	}
	imports.finalize()

	var source strings.Builder
	source.WriteString(generatedFileHeader)
	source.WriteString("package modules\n\n")
	writeImports(&source, imports)
	writeSeedDeclarations(&source, modules)
	writeDescriptorDeclarations(&source, fragments, imports)
	writeInfrastructureDeclarations(&source, fragments, hasOutbox, len(controllers) > 0 || hasSeed, hasAuthProviders(graph.Providers()))
	writeBaseProviderDeclarations(&source, fragments, imports)
	writeServiceAdapterDeclarations(&source, services, imports)
	writeControllerDeclarations(&source, controllers, imports)
	writeGRPCRegistrarDeclaration(&source, registrars, imports)
	writeGeneratedFunction(&source, graph, modules, fragments, descriptorProviders, providers, ordered, dependencies, services, controllers, imports)
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, renderError("CG079", "生成模块注册表语法无效: "+err.Error(), Position{})
	}
	return bytes.Clone(formatted), nil
}

type renderModule struct {
	config     ConfigDeclaration
	key        string
	references []Reference
	seedDB     bool
	seedMenu   bool
}

func writeSeedDeclarations(source *strings.Builder, modules []renderModule) {
	for _, current := range modules {
		identifier := generatedIdentifier(current.key)
		if current.seedDB {
			fmt.Fprintf(source, "//go:embed %s/db.json\nvar seedDB_%s []byte\n\n", current.key, identifier)
		}
		if current.seedMenu {
			fmt.Fprintf(source, "//go:embed %s/menu.json\nvar seedMenu_%s []byte\n\n", current.key, identifier)
		}
	}
}

type renderComponent struct {
	component   Component
	constructor Constructor
}

type renderService struct {
	declaration ServiceDeclaration
	module      string
}

type renderController struct {
	declaration ControllerDeclaration
	module      string
}

type renderGRPCRegistrar struct {
	declaration GRPCRegistrarDeclaration
	module      string
}

func renderGRPCRegistrars(model *Model) []renderGRPCRegistrar {
	var result []renderGRPCRegistrar
	for _, current := range model.modules {
		for _, declaration := range current.registrars {
			result = append(result, renderGRPCRegistrar{declaration: declaration, module: current.identity.Key()})
		}
	}
	sort.Slice(result, func(left, right int) bool {
		if result[left].module != result[right].module {
			return result[left].module < result[right].module
		}

		return result[left].declaration.packagePath < result[right].declaration.packagePath
	})

	return result
}

func renderControllers(model *Model) []renderController {
	var result []renderController
	for _, current := range model.modules {
		for _, declaration := range current.controllers {
			result = append(result, renderController{declaration: declaration, module: current.identity.Key()})
		}
	}
	sort.Slice(result, func(left, right int) bool {
		if result[left].module != result[right].module {
			return result[left].module < result[right].module
		}
		if result[left].declaration.packagePath != result[right].declaration.packagePath {
			return result[left].declaration.packagePath < result[right].declaration.packagePath
		}

		return result[left].declaration.name < result[right].declaration.name
	})

	return result
}

func renderServices(model *Model) []renderService {
	var result []renderService
	for _, current := range model.modules {
		for _, declaration := range current.services {
			result = append(result, renderService{declaration: declaration, module: current.identity.Key()})
		}
	}
	sort.Slice(result, func(left, right int) bool {
		if result[left].module != result[right].module {
			return result[left].module < result[right].module
		}
		if result[left].declaration.packagePath != result[right].declaration.packagePath {
			return result[left].declaration.packagePath < result[right].declaration.packagePath
		}

		return result[left].declaration.name < result[right].declaration.name
	})

	return result
}

func renderModel(model *Model) ([]renderModule, map[string]Constructor, error) {
	modules := make([]renderModule, len(model.modules))
	constructors := make(map[string]Constructor)
	for index, current := range model.modules {
		if current.identity.Key() == "" || current.config.packagePath == "" || current.config.packageName == "" || current.config.name == "" || current.config.description == "" {
			return nil, nil, renderError("CG073", "模块静态描述信息不完整", current.config.position)
		}
		modules[index] = renderModule{config: current.config, key: current.identity.Key(), references: current.references, seedDB: current.seedDB, seedMenu: current.seedMenu}
		for _, constructor := range current.constructors {
			if constructor.packagePath == "" || constructor.packageName == "" {
				return nil, nil, renderError("CG074", "构造器源码信息不完整", constructor.position)
			}
			key := componentKey(current.identity.Key(), constructor.packagePath, constructor.name)
			if _, exists := constructors[key]; exists {
				return nil, nil, renderError("CG075", "构造器定义重复", constructor.position)
			}
			constructors[key] = constructor
		}
	}
	sort.Slice(modules, func(left, right int) bool { return modules[left].key < modules[right].key })
	return modules, constructors, nil
}

func renderFragments(model *Model, descriptors *DescriptorSet, modules []renderModule) ([]DescriptorFragment, error) {
	known := make(map[string]bool, len(modules))
	expected := make(map[string]Position)
	for _, current := range modules {
		known[current.key] = true
	}
	for _, current := range model.modules {
		for _, declaration := range current.entities {
			expected[descriptorKey(current.identity.Key(), declaration.packagePath, declaration.name)] = declaration.position
		}
	}
	fragments := descriptors.Fragments()
	seen := make(map[string]bool, len(fragments))
	for _, fragment := range fragments {
		if !known[fragment.module] {
			return nil, renderError("CG076", "Descriptor 所属模块不存在", Position{})
		}
		key := descriptorKey(fragment.module, fragment.entityPackage, fragment.entity)
		if _, exists := expected[key]; !exists {
			return nil, renderError("CG080", "Descriptor 不属于已发现实体", Position{})
		}
		if seen[key] {
			return nil, renderError("CG081", "实体存在重复 Descriptor", Position{})
		}
		seen[key] = true
	}
	for _, key := range sortedRenderKeys(expected) {
		position := expected[key]
		if !seen[key] {
			return nil, renderError("CG082", "实体缺少 Descriptor", position)
		}
	}
	sort.Slice(fragments, func(left, right int) bool {
		if fragments[left].module != fragments[right].module {
			return fragments[left].module < fragments[right].module
		}
		if fragments[left].entityPackage != fragments[right].entityPackage {
			return fragments[left].entityPackage < fragments[right].entityPackage
		}
		return fragments[left].entity < fragments[right].entity
	})
	return fragments, nil
}

func renderComponents(graph *Graph, constructors map[string]Constructor) ([]renderComponent, error) {
	ordered := make([]renderComponent, len(graph.order))
	seen := make(map[string]bool, len(graph.order))
	for index, component := range graph.order {
		key := componentKey(component.module, component.packagePath, component.name)
		constructor, exists := constructors[key]
		if !exists {
			return nil, renderError("CG077", "Provider 图包含未知构造器", component.position)
		}
		if seen[key] {
			return nil, renderError("CG078", "Provider 图包含重复构造器", component.position)
		}
		seen[key] = true
		ordered[index] = renderComponent{component: component, constructor: constructor}
	}
	if len(seen) != len(constructors) {
		for _, key := range sortedRenderKeys(constructors) {
			constructor := constructors[key]
			if !seen[key] {
				return nil, renderError("CG083", "Provider 图缺少构造器", constructor.position)
			}
		}
	}
	return ordered, nil
}

func renderProviders(graph *Graph, fragments []DescriptorFragment) ([]Provider, map[string]Provider, error) {
	providers := append([]Provider(nil), graph.providers...)
	sort.Slice(providers, func(left, right int) bool {
		first, second := providers[left], providers[right]
		if first.module != second.module {
			return first.module < second.module
		}
		if first.packagePath != second.packagePath {
			return first.packagePath < second.packagePath
		}
		if first.name != second.name {
			return first.name < second.name
		}
		if first.typ != second.typ {
			return first.typ < second.typ
		}
		return first.kind < second.kind
	})
	known := make(map[string]Provider, len(providers))
	for _, provider := range providers {
		if moduleProviderKind(provider.kind) == "" {
			return nil, nil, renderError("CG085", "Provider 类别无法渲染", Position{})
		}
		key := renderProviderKey(provider)
		if _, exists := known[key]; exists {
			return nil, nil, renderError("CG085", "Provider 图包含重复 Provider", Position{})
		}
		known[key] = provider
	}
	descriptorProviders := make(map[string]Provider, len(fragments))
	seenDescriptors := make(map[string]bool, len(fragments))
	seenBases := make(map[string]bool, len(fragments))
	for _, fragment := range fragments {
		expected := Provider{
			kind:        ProviderKindDescriptor,
			module:      fragment.module,
			packagePath: fragment.entityPackage,
			name:        fragment.provider.name,
			typ:         fragment.provider.typ,
		}
		provider, exists := known[renderProviderKey(expected)]
		if !exists || provider.typ != expected.typ {
			return nil, nil, renderError("CG086", "Descriptor 缺少对应 Provider", fragment.provider.position)
		}
		key := descriptorKey(fragment.module, fragment.entityPackage, fragment.entity)
		descriptorProviders[key] = provider
		seenDescriptors[renderProviderKey(provider)] = true

		expectedBase := Provider{
			kind:        ProviderKindBase,
			module:      fragment.module,
			packagePath: fragment.entityPackage,
			name:        fragment.baseProvider.name,
			typ:         fragment.baseProvider.typ,
		}
		baseProvider, exists := known[renderProviderKey(expectedBase)]
		if !exists || baseProvider.typ != expectedBase.typ {
			return nil, nil, renderError("CG097", "Descriptor 缺少对应 Base Provider", fragment.baseProvider.position)
		}
		seenBases[renderProviderKey(baseProvider)] = true
	}
	for _, provider := range providers {
		if provider.kind == ProviderKindDescriptor && !seenDescriptors[renderProviderKey(provider)] {
			return nil, nil, renderError("CG086", "Descriptor Provider 缺少对应 Descriptor", Position{})
		}
		if provider.kind == ProviderKindBase && !seenBases[renderProviderKey(provider)] {
			return nil, nil, renderError("CG097", "Base Provider 缺少对应 Descriptor", Position{})
		}
	}
	return providers, descriptorProviders, nil
}

func renderDependencies(graph *Graph, components []renderComponent, providers []Provider) ([]Dependency, error) {
	componentIndexes := make(map[string]int, len(components))
	for index, current := range components {
		componentIndexes[componentKey(current.component.module, current.component.packagePath, current.component.name)] = index
	}
	knownProviders := make(map[string]Provider, len(providers))
	for _, provider := range providers {
		knownProviders[renderProviderKey(provider)] = provider
	}
	dependencies := append([]Dependency(nil), graph.dependencies...)
	for _, dependency := range dependencies {
		consumer := dependency.consumer
		if _, exists := componentIndexes[componentKey(consumer.module, consumer.packagePath, consumer.name)]; !exists {
			return nil, renderError("CG087", "Provider 图依赖包含未知消费组件", consumer.position)
		}
		provider, exists := knownProviders[renderProviderKey(dependency.provider)]
		if !exists || provider.typ != dependency.provider.typ {
			return nil, renderError("CG087", "Provider 图依赖包含未知 Provider", dependency.position)
		}
	}
	sort.Slice(dependencies, func(left, right int) bool {
		first, second := dependencies[left], dependencies[right]
		firstIndex := componentIndexes[componentKey(first.consumer.module, first.consumer.packagePath, first.consumer.name)]
		secondIndex := componentIndexes[componentKey(second.consumer.module, second.consumer.packagePath, second.consumer.name)]
		if firstIndex != secondIndex {
			return firstIndex < secondIndex
		}
		if first.parameterIndex != second.parameterIndex {
			return first.parameterIndex < second.parameterIndex
		}
		return renderProviderKey(first.provider) < renderProviderKey(second.provider)
	})
	return dependencies, nil
}

func validateGeneratedIdentifiers(
	fragments []DescriptorFragment,
	components []renderComponent,
	services []renderService,
	controllers []renderController,
) error {
	used := make(map[string]bool, len(fragments)*4+len(components))
	for _, fragment := range fragments {
		for _, identifier := range []string{
			fragment.baseProvider.name,
			fragment.doName,
			doValueTypeName(fragment),
			compiledDescriptorTypeName(fragment),
			descriptorFunctionName(fragment),
		} {
			if used[identifier] {
				return renderError("CG084", "生成标识符重复: "+identifier, Position{})
			}
			used[identifier] = true
		}
	}
	for _, current := range services {
		for _, action := range serviceActionNames {
			for _, identifier := range []string{
				serviceActionModeName(current, action),
				serviceActionAdapterName(current, action),
			} {
				if used[identifier] {
					return renderError("CG084", "生成标识符重复: "+identifier, current.declaration.position)
				}
				used[identifier] = true
			}
		}
		for _, hook := range []string{"ModifyBefore", "ModifyAfter"} {
			identifier := serviceActionAdapterName(current, hook)
			if used[identifier] {
				return renderError("CG084", "生成标识符重复: "+identifier, current.declaration.position)
			}
			used[identifier] = true
		}
	}
	for _, current := range controllers {
		identifier := controllerFunctionName(current)
		if used[identifier] {
			return renderError("CG084", "生成标识符重复: "+identifier, current.declaration.position)
		}
		used[identifier] = true
	}
	return nil
}

func writeBaseProviderDeclarations(source *strings.Builder, fragments []DescriptorFragment, imports *importManager) {
	for _, fragment := range fragments {
		entityAlias := imports.alias(fragment.entityPackage)
		fmt.Fprintf(
			source,
			"func %s(descriptor coreentity.Descriptor[%s.%s, uint64], runtime *coredb.Runtime, recycler *corerecycle.Store) (*coreservice.Base[%s.%s, uint64], error) {\n",
			fragment.baseProvider.name,
			entityAlias,
			fragment.entity,
			entityAlias,
			fragment.entity,
		)
		fmt.Fprintf(source, "\treturn coreservice.NewBase[%s.%s, uint64](descriptor, runtime, recycler)\n", entityAlias, fragment.entity)
		source.WriteString("}\n\n")
	}
}

func writeServiceAdapterDeclarations(source *strings.Builder, services []renderService, imports *importManager) {
	for _, current := range services {
		declaration := current.declaration
		for _, action := range declaration.actions {
			fmt.Fprintf(
				source,
				"const %s coreservice.ActionMode = coreservice.ActionMode%s\n\n",
				serviceActionModeName(current, action.name),
				serviceActionModeConstant(action.mode),
			)
			writeServiceActionAdapter(source, current, action, imports)
		}
		writeHookAdapter(source, current, imports, "ModifyBefore", declaration.hasBefore)
		writeHookAdapter(source, current, imports, "ModifyAfter", declaration.hasAfter)
	}
}

func writeServiceActionAdapter(source *strings.Builder, current renderService, action ServiceAction, imports *importManager) {
	signature := serviceActionSignature(current.declaration, action)
	if signature == nil {
		return
	}
	serviceType := "*" + imports.alias(current.declaration.packagePath) + "." + current.declaration.name
	requestType := types.TypeString(signature.Params().At(1).Type(), importsQualifier(imports))
	result := "error"
	if signature.Results().Len() == 2 {
		resultType := "any"
		if action.name == "Add" {
			resultType = types.TypeString(signature.Results().At(0).Type(), importsQualifier(imports))
		}
		result = "(" + resultType + ", error)"
	}
	fmt.Fprintf(
		source,
		"func %s(ctx context.Context, instance %s, input %s) %s {\n\treturn %s(ctx, input)\n}\n\n",
		serviceActionAdapterName(current, action.name),
		serviceType,
		requestType,
		result,
		serviceActionTarget(current.declaration.actions, action.name),
	)
}

func serviceActionSignature(declaration ServiceDeclaration, action ServiceAction) *types.Signature {
	if action.mode == ServiceActionBase {
		return baseActionSignature(declaration.typ, action.name)
	}
	selection := types.NewMethodSet(types.NewPointer(declaration.typ)).Lookup(nil, action.name)
	if selection == nil {
		return nil
	}
	signature, _ := selection.Obj().Type().(*types.Signature)

	return signature
}

func writeControllerDeclarations(source *strings.Builder, controllers []renderController, imports *importManager) {
	for _, current := range controllers {
		declaration := current.declaration
		parameters := make([]string, len(declaration.parameterTypes))
		arguments := make([]string, len(declaration.parameterTypes))
		for index, parameter := range declaration.parameterTypes {
			arguments[index] = "dependency" + strconv.Itoa(index)
			parameters[index] = arguments[index] + " " + types.TypeString(parameter, importsQualifier(imports))
		}
		fmt.Fprintf(
			source,
			"func %s(%s) corecontroller.Definition {\n\treturn %s.%s(%s)\n}\n\n",
			controllerFunctionName(current),
			strings.Join(parameters, ", "),
			imports.alias(declaration.packagePath),
			declaration.name,
			strings.Join(arguments, ", "),
		)
	}
}

func writeHookAdapter(source *strings.Builder, current renderService, imports *importManager, hook string, exists bool) {
	declaration := current.declaration
	entityType := types.TypeString(declaration.entityType, importsQualifier(imports))
	idType := types.TypeString(declaration.idType, importsQualifier(imports))
	serviceType := "*" + imports.alias(declaration.packagePath) + "." + declaration.name
	fmt.Fprintf(
		source,
		"func %s(ctx context.Context, instance %s, mutation *coreservice.Mutation[%s, %s]) error {\n",
		serviceActionAdapterName(current, hook),
		serviceType,
		entityType,
		idType,
	)
	if exists {
		fmt.Fprintf(source, "\treturn instance.%s(ctx, mutation)\n", hook)
	} else {
		source.WriteString("\treturn nil\n")
	}
	source.WriteString("}\n\n")
}

func writeImports(source *strings.Builder, imports *importManager) {
	paths := imports.pathsInOrder()
	if len(paths) == 0 {
		return
	}
	source.WriteString("import (\n")
	for _, path := range paths {
		fmt.Fprintf(source, "\t%s %q\n", imports.alias(path), path)
	}
	source.WriteString(")\n\n")
}

func writeDescriptorDeclarations(source *strings.Builder, fragments []DescriptorFragment, imports *importManager) {
	for _, fragment := range fragments {
		source.WriteString(fragment.doDeclaration)
		source.WriteByte('\n')
		writeDOValueDeclaration(source, fragment)
		writeCompiledDescriptorDeclaration(source, fragment, imports)
		writeDescriptorFunction(source, fragment, imports)
	}
}

func writeInfrastructureDeclarations(source *strings.Builder, fragments []DescriptorFragment, hasOutbox, hasHTTP, hasAuth bool) {
	source.WriteString("type infrastructureConfig struct {\n")
	source.WriteString("\tCool struct {\n")
	source.WriteString("\t\tCRUD crud.Config `json:\"crud\"`\n")
	source.WriteString("\t\tOutbox outbox.Config `json:\"outbox\"`\n")
	source.WriteString("\t\tTransports struct {\n")
	source.WriteString("\t\t\tHTTP apphttp.Config `json:\"http\"`\n")
	source.WriteString("\t\t\tGRPC coolgrpc.Config `json:\"grpc\"`\n")
	source.WriteString("\t\t} `json:\"transports\"`\n")
	if hasAuth {
		source.WriteString("\t\tAuth struct {\n")
		source.WriteString("\t\t\tJWT auth.JWTConfig `json:\"jwt\"`\n")
		source.WriteString("\t\t\tSession auth.SessionConfig `json:\"session\"`\n")
		source.WriteString("\t\t} `json:\"auth\"`\n")
	}
	source.WriteString("\t} `json:\"cool\"`\n")
	source.WriteString("\tDatabase map[string]gdb.ConfigGroup `json:\"database\"`\n")
	source.WriteString("\tRedis map[string]gredis.Config `json:\"redis\"`\n")
	source.WriteString("}\n\n")
	source.WriteString("func generatedInfrastructureConfig(ctx context.Context, source configuration.Source) (infrastructureConfig, error) {\n")
	source.WriteString("\tdefaults := infrastructureConfig{}\n")
	source.WriteString("\tdefaults.Cool.CRUD = crud.DefaultConfig()\n")
	source.WriteString("\tdefaults.Cool.Outbox = outbox.DefaultConfig()\n")
	source.WriteString("\tdefaults.Cool.Transports.HTTP = apphttp.DefaultConfig()\n")
	source.WriteString("\tdefaults.Cool.Transports.GRPC = coolgrpc.DefaultConfig()\n")
	if hasAuth {
		source.WriteString("\tdefaults.Cool.Auth.JWT = auth.DefaultJWTConfig()\n")
		source.WriteString("\tdefaults.Cool.Auth.Session = auth.DefaultSessionConfig()\n")
	}
	source.WriteString("\tresult, err := configuration.Load(ctx, defaults, source)\n")
	source.WriteString("\tif err != nil {\n\t\treturn infrastructureConfig{}, exception.WrapCore(err, \"基础设施配置无效\")\n\t}\n")
	source.WriteString("\tconfig := result.Value()\n")
	source.WriteString("\tfor group, node := range config.Redis {\n")
	source.WriteString("\t\tgredis.SetConfig(&node, group)\n")
	source.WriteString("\t}\n")
	source.WriteString("\tif err = config.Cool.Outbox.Validate(); err != nil {\n\t\treturn infrastructureConfig{}, exception.WrapCore(err, \"Outbox 配置无效\")\n\t}\n")
	source.WriteString("\tif config.Cool.Outbox.Enabled && len(config.Database[config.Cool.Outbox.DatabaseGroup]) == 0 {\n")
	source.WriteString("\t\treturn infrastructureConfig{}, exception.Core(\"Outbox Database Group 不存在\")\n\t}\n")
	source.WriteString("\treturn config, nil\n")
	source.WriteString("}\n\n")
	if len(fragments) == 0 && !hasOutbox && !hasHTTP {
		return
	}
	source.WriteString("func generatedDataRuntime(ctx context.Context, config infrastructureConfig, descriptors ...coreentity.RuntimeDescriptor) (*coredb.Runtime, *corerecycle.Store, error) {\n")
	source.WriteString("\tgroup := config.Cool.Outbox.DatabaseGroup\n")
	source.WriteString("\ttables := make([]string, len(descriptors))\n")
	source.WriteString("\tfor index, descriptor := range descriptors {\n\t\ttables[index] = descriptor.Table()\n\t}\n")
	source.WriteString("\tif len(descriptors) > 0 && config.Cool.CRUD.SoftDelete {\n\t\ttables = append(tables, corerecycle.TableName)\n\t}\n")
	if hasOutbox {
		source.WriteString("\ttables = append(tables, dbschema.OutboxTableName, dbschema.InboxTableName)\n")
	}
	source.WriteString("\tbootstrap, err := coredb.New(ctx, coredb.Config{Group: group, Nodes: config.Database[group]})\n")
	source.WriteString("\tif err != nil {\n\t\treturn nil, nil, err\n\t}\n")
	source.WriteString("\tif len(descriptors) > 0 {\n")
	source.WriteString("\t\tmanager, err := dbschema.New(bootstrap.DB(), bootstrap.Dialect())\n")
	source.WriteString("\t\tif err != nil {\n\t\t\treturn nil, nil, exception.WrapCore(err, \"创建 Schema 管理器失败\")\n\t\t}\n")
	source.WriteString("\t\tmetadata := make([]coreentity.Metadata, len(descriptors))\n")
	source.WriteString("\t\tfor index, descriptor := range descriptors {\n\t\t\tmetadata[index] = descriptor\n\t\t}\n")
	source.WriteString("\t\tif _, err = manager.Apply(ctx, dbschema.Sync, metadata...); err != nil {\n\t\t\treturn nil, nil, exception.WrapCore(err, \"同步业务表结构失败\")\n\t\t}\n")
	source.WriteString("\t}\n")
	source.WriteString("\tif len(descriptors) > 0 && config.Cool.CRUD.SoftDelete {\n")
	source.WriteString("\t\tbootstrapRecycler, err := corerecycle.New(bootstrap, config.Cool.CRUD, descriptors...)\n")
	source.WriteString("\t\tif err != nil {\n\t\t\treturn nil, nil, err\n\t\t}\n")
	source.WriteString("\t\tif err = bootstrapRecycler.Prepare(ctx, dbschema.Sync); err != nil {\n\t\t\treturn nil, nil, err\n\t\t}\n")
	source.WriteString("\t}\n")
	source.WriteString("\truntime, err := coredb.New(ctx, coredb.Config{Group: group, Nodes: config.Database[group], TransactionTables: tables})\n")
	source.WriteString("\tif err != nil {\n\t\treturn nil, nil, err\n\t}\n")
	source.WriteString("\tvar store *corerecycle.Store\n")
	source.WriteString("\tif len(descriptors) > 0 {\n")
	source.WriteString("\t\tstore, err = corerecycle.New(runtime, config.Cool.CRUD, descriptors...)\n")
	source.WriteString("\t\tif err != nil {\n\t\t\treturn nil, nil, err\n\t\t}\n\t}\n")
	source.WriteString("\treturn runtime, store, nil\n")
	source.WriteString("}\n\n")
}

func writeDOValueDeclaration(source *strings.Builder, fragment DescriptorFragment) {
	name := doValueTypeName(fragment)
	fmt.Fprintf(source, "type %s struct {\n\tstate coreentity.DOValue\n\tdata %s\n}\n\n", name, fragment.doName)
	fmt.Fprintf(source, "func (value *%s) Has(field string) bool { return value.state.Has(field) }\n\n", name)
	fmt.Fprintf(source, "func (value *%s) IsNull(field string) bool { return value.state.IsNull(field) }\n\n", name)
	fmt.Fprintf(source, "func (value *%s) SetColumn(field string, input any) error {\n", name)
	source.WriteString("\tif err := value.state.SetColumn(field, input); err != nil {\n\t\treturn err\n\t}\n")
	source.WriteString("\tif value.state.IsNull(field) {\n\t\tinput = gdb.Raw(\"NULL\")\n\t}\n")
	source.WriteString("\tswitch field {\n")
	for _, field := range fragment.fields {
		fmt.Fprintf(source, "\tcase %q:\n\t\tvalue.data.%s = input\n", field.json, field.declaration)
	}
	source.WriteString("\t}\n\treturn nil\n}\n\n")
	fmt.Fprintf(source, "func (value *%s) DBData() any { return value.data }\n\n", name)
}

func writeCompiledDescriptorDeclaration(source *strings.Builder, fragment DescriptorFragment, imports *importManager) {
	var (
		descriptorName = compiledDescriptorTypeName(fragment)
		doValueName    = doValueTypeName(fragment)
		entityAlias    = imports.alias(fragment.entityPackage)
	)
	fmt.Fprintf(source, "type %s struct {\n\tcoreentity.Descriptor[%s.%s, uint64]\n}\n\n", descriptorName, entityAlias, fragment.entity)
	fmt.Fprintf(source, "func (descriptor %s) NewDO() coreentity.DOValue {\n", descriptorName)
	fmt.Fprintf(source, "\treturn &%s{state: descriptor.Descriptor.NewDO()}\n", doValueName)
	source.WriteString("}\n\n")
}

func writeDescriptorFunction(source *strings.Builder, fragment DescriptorFragment, imports *importManager) {
	var (
		name           = descriptorFunctionName(fragment)
		descriptorName = compiledDescriptorTypeName(fragment)
		entityAlias    = imports.alias(fragment.entityPackage)
	)
	fmt.Fprintf(source, "func %s() coreentity.Descriptor[%s.%s, uint64] {\n", name, entityAlias, fragment.entity)
	fmt.Fprintf(source, "\tdescriptor, err := coreentity.Compile[%s.%s, uint64](%s.%sSchema())\n", entityAlias, fragment.entity, entityAlias, fragment.entity)
	source.WriteString("\tif err != nil {\n\t\tpanic(err)\n\t}\n")
	fmt.Fprintf(source, "\treturn %s{Descriptor: descriptor}\n}\n\n", descriptorName)
}

func writeGRPCRegistrarDeclaration(source *strings.Builder, registrars []renderGRPCRegistrar, imports *importManager) {
	source.WriteString("type generatedGRPCRegistrar struct{}\n\n")
	source.WriteString("func (generatedGRPCRegistrar) Register(server *grpcx.GrpcServer) error {\n")
	for _, current := range registrars {
		call := imports.alias(current.declaration.packagePath) + "." + current.declaration.name + "(server)"
		fmt.Fprintf(source, "\tif err := %s; err != nil {\n", call)
		fmt.Fprintf(source, "\t\treturn exception.WrapCore(err, %q)\n", "注册 gRPC 服务 "+current.declaration.packagePath+" 失败")
		source.WriteString("\t}\n")
	}
	source.WriteString("\treturn nil\n}\n\n")
	source.WriteString("func GRPCRegistrar() coolgrpc.GRPCRegistrar { return generatedGRPCRegistrar{} }\n\n")
}

func componentDependencies(component Component, dependencies []Dependency) []Dependency {
	var result []Dependency
	for _, dependency := range dependencies {
		consumer := dependency.consumer
		if consumer.module == component.module && consumer.packagePath == component.packagePath && consumer.name == component.name {
			result = append(result, dependency)
		}
	}
	sort.Slice(result, func(left, right int) bool {
		return result[left].parameterIndex < result[right].parameterIndex
	})
	return result
}

func writeGeneratedFunction(
	source *strings.Builder,
	graph *Graph,
	modules []renderModule,
	fragments []DescriptorFragment,
	descriptorProviders map[string]Provider,
	providers []Provider,
	components []renderComponent,
	dependencies []Dependency,
	services []renderService,
	controllers []renderController,
	imports *importManager,
) {
	producers := graph.Producers()
	consumers := graph.Consumers()
	publisher, hasPublisher := graph.Publisher()
	consumerAdapter, hasConsumerAdapter := graph.ConsumerAdapter()
	hasProducers := len(producers) > 0
	hasConsumers := len(consumers) > 0
	workerDefinition := Component{module: frameworkModuleKey, packagePath: outboxPackagePath, name: "NewWorker"}
	consumerRuntimeDefinition := Component{module: frameworkModuleKey, packagePath: outboxPackagePath, name: "NewConsumerRuntime"}
	graphProviders := append([]Provider(nil), providers...)
	graphProviders = appendProviderIfMissing(graphProviders, Provider{kind: ProviderKindComponent, module: frameworkModuleKey, packagePath: appHTTPPackagePath, name: "New", typ: "*" + appHTTPPackagePath + ".Transport"})
	graphProviders = appendProviderIfMissing(graphProviders, Provider{kind: ProviderKindComponent, module: frameworkModuleKey, packagePath: grpcPackagePath, name: "New", typ: "*" + grpcPackagePath + ".Transport"})
	graphProviders = appendProviderIfMissing(graphProviders, Provider{kind: ProviderKindComponent, module: frameworkModuleKey, packagePath: databasePackagePath, name: "Runtime", typ: "*" + databasePackagePath + ".Runtime"})
	if hasProducers {
		graphProviders = appendProviderIfMissing(graphProviders, Provider{kind: ProviderKindComponent, module: workerDefinition.module, packagePath: workerDefinition.packagePath, name: workerDefinition.name, typ: "*" + outboxPackagePath + ".Worker"})
	}
	if hasConsumers {
		graphProviders = appendProviderIfMissing(graphProviders, Provider{kind: ProviderKindComponent, module: consumerRuntimeDefinition.module, packagePath: consumerRuntimeDefinition.packagePath, name: consumerRuntimeDefinition.name, typ: "*" + outboxPackagePath + ".ConsumerRuntime"})
	}
	source.WriteString("func generatedGraph() module.Graph {\n")
	source.WriteString("\treturn module.MustBuildGraph(module.GraphInput{\n")
	source.WriteString("\t\tModules: []module.ModuleDefinition{\n")
	for _, current := range modules {
		fmt.Fprintf(source, "\t\t\t{Key: %q, Name: %q, Description: %q, Order: %d", current.key, current.config.name, current.config.description, current.config.order)
		writeReferences(source, "Middlewares", current.references, imports)
		writeReferences(source, "GlobalMiddlewares", current.references, imports)
		source.WriteString("},\n")
	}
	source.WriteString("\t\t\t{Key: \".framework\", Name: \"Cool Framework\", Description: \"应用基础设施\"},\n")
	source.WriteString("\t\t},\n")
	if len(controllers) > 0 {
		source.WriteString("\t\tControllers: []coreroute.ControllerDefinition{\n")
		for _, current := range controllers {
			writeControllerDefinition(source, current)
		}
		source.WriteString("\t\t},\n")
		source.WriteString("\t\tRoutes: []coreroute.Definition{\n")
		for _, current := range controllers {
			for _, route := range current.declaration.routes {
				writeRouteDefinition(source, current, route)
			}
		}
		source.WriteString("\t\t},\n")
	}
	source.WriteString("\t\tProviders: []module.ProviderDefinition{\n")
	for _, provider := range graphProviders {
		source.WriteString("\t\t\t")
		writeProviderDefinition(source, provider, false)
		source.WriteString(",\n")
	}
	source.WriteString("\t\t},\n")
	definedComponents := make(map[string]bool, len(graphProviders))
	componentDefinitions := make([]Component, 0, len(graphProviders))
	constructorsByComponent := make(map[string]Constructor, len(components))
	for _, current := range components {
		key := componentKey(current.component.module, current.component.packagePath, current.component.name)
		constructorsByComponent[key] = current.constructor
	}
	assemblyComponents := append([]renderComponent(nil), components...)
	if authorizer, exists := authorizerComponent(components); exists {
		assemblyComponents = authorizerPrerequisites(authorizer, components, dependencies)
		for _, current := range components {
			if !authorizerDependency(authorizer, current, components, dependencies) {
				assemblyComponents = append(assemblyComponents, current)
			}
		}
	}
	for _, provider := range graphProviders {
		if provider.kind != ProviderKindComponent && provider.kind != ProviderKindConsumerDefinition {
			continue
		}
		if provider.packagePath == appHTTPPackagePath || provider.packagePath == grpcPackagePath {
			continue
		}
		definition := Component{module: provider.module, packagePath: provider.packagePath, name: provider.name}
		key := componentKey(definition.module, definition.packagePath, definition.name)
		if definedComponents[key] || constructorsByComponent[key].name != "" {
			continue
		}
		componentDefinitions = append(componentDefinitions, definition)
		definedComponents[key] = true
	}
	for _, current := range assemblyComponents {
		key := componentKey(current.component.module, current.component.packagePath, current.component.name)
		if definedComponents[key] {
			continue
		}
		componentDefinitions = append(componentDefinitions, current.component)
		definedComponents[key] = true
	}
	for _, provider := range graphProviders {
		if (provider.packagePath != appHTTPPackagePath && provider.packagePath != grpcPackagePath) || provider.name != "New" {
			continue
		}
		definition := Component{module: provider.module, packagePath: provider.packagePath, name: provider.name}
		key := componentKey(definition.module, definition.packagePath, definition.name)
		if definedComponents[key] {
			continue
		}
		componentDefinitions = append(componentDefinitions, definition)
		definedComponents[key] = true
	}
	source.WriteString("\t\tComponents: []module.ComponentDefinition{\n")
	for _, definition := range componentDefinitions {
		writeComponentDefinition(source, definition)
	}
	source.WriteString("\t\t},\n")
	source.WriteString("\t\tLifecycles: []module.LifecycleDefinition{\n")
	for _, definition := range componentDefinitions {
		constructor := constructorsByComponent[componentKey(definition.module, definition.packagePath, definition.name)]
		hasInitializer := constructor.hasInitializer
		hasStarter := constructor.hasStarter
		hasStopper := constructor.hasStopper
		hasSupervisor := false
		if hasProducers && sameComponent(definition, workerDefinition) {
			hasStarter = true
			hasStopper = true
			hasSupervisor = true
		}
		if hasConsumers && sameComponent(definition, consumerRuntimeDefinition) {
			hasInitializer = true
			hasStarter = true
			hasStopper = true
			hasSupervisor = true
		}
		fmt.Fprintf(
			source,
			"\t\t\t{Component: module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, Initializer: %t, Starter: %t, Stopper: %t, Supervisor: %t},\n",
			definition.module,
			definition.packagePath,
			definition.name,
			hasInitializer,
			hasStarter,
			hasStopper,
			hasSupervisor,
		)
	}
	source.WriteString("\t\t},\n")
	source.WriteString("\t\tTransports: []module.ComponentDefinition{\n")
	for _, current := range components {
		if !current.constructor.hasTransport {
			continue
		}
		fmt.Fprintf(source, "\t\t\t{Module: %q, PackagePath: %q, Name: %q},\n", current.component.module, current.component.packagePath, current.component.name)
	}
	fmt.Fprintf(source, "\t\t\t{Module: %q, PackagePath: %q, Name: \"New\"},\n", frameworkModuleKey, appHTTPPackagePath)
	fmt.Fprintf(source, "\t\t\t{Module: %q, PackagePath: %q, Name: \"New\"},\n", frameworkModuleKey, grpcPackagePath)
	source.WriteString("\t\t},\n")
	source.WriteString("\t\tDependencies: []module.DependencyDefinition{\n")
	for _, dependency := range dependencies {
		consumer := dependency.consumer
		fmt.Fprintf(source, "\t\t\t{Consumer: module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, ParameterIndex: %d, Provider: ", consumer.module, consumer.packagePath, consumer.name, dependency.parameterIndex)
		writeProviderDefinition(source, dependency.provider, true)
		source.WriteString("},\n")
	}
	if hasProducers && hasPublisher {
		fmt.Fprintf(source, "\t\t\t{Consumer: module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, ParameterIndex: 0, Provider: ", workerDefinition.module, workerDefinition.packagePath, workerDefinition.name)
		writeProviderDefinition(source, componentProvider(graph, publisher), true)
		source.WriteString("},\n")
	}
	if hasConsumers && hasConsumerAdapter {
		fmt.Fprintf(source, "\t\t\t{Consumer: module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, ParameterIndex: 0, Provider: ", consumerRuntimeDefinition.module, consumerRuntimeDefinition.packagePath, consumerRuntimeDefinition.name)
		writeProviderDefinition(source, componentProvider(graph, consumerAdapter), true)
		source.WriteString("},\n")
		for index, consumer := range consumers {
			fmt.Fprintf(source, "\t\t\t{Consumer: module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, ParameterIndex: %d, Provider: ", consumerRuntimeDefinition.module, consumerRuntimeDefinition.packagePath, consumerRuntimeDefinition.name, index+1)
			writeProviderDefinition(source, componentProvider(graph, consumer), true)
			source.WriteString("},\n")
		}
	}
	source.WriteString("\t\t},\n")
	source.WriteString("\t\tDescriptors: []module.DescriptorDefinition{\n")
	for _, fragment := range fragments {
		key := descriptorKey(fragment.module, fragment.entityPackage, fragment.entity)
		fmt.Fprintf(source, "\t\t\t{Module: %q, Table: %q, Provider: ", fragment.module, fragment.table)
		writeProviderDefinition(source, descriptorProviders[key], true)
		source.WriteString("},\n")
	}
	source.WriteString("\t\t},\n")
	source.WriteString("\t\tOutbox: module.OutboxDefinition{\n")
	writeOutboxRoleDefinitions(source, "Producers", producers)
	writeOutboxRoleDefinitions(source, "Consumers", consumers)
	if hasPublisher {
		writeOutboxRoleDefinitions(source, "Publishers", []Component{publisher})
	}
	if hasConsumerAdapter {
		writeOutboxRoleDefinitions(source, "ConsumerAdapters", []Component{consumerAdapter})
	}
	if hasProducers {
		writeOutboxRoleDefinitions(source, "Workers", []Component{workerDefinition})
	}
	if hasConsumers {
		writeOutboxRoleDefinitions(source, "ConsumerRuntimes", []Component{consumerRuntimeDefinition})
	}
	source.WriteString("\t\t},\n")
	source.WriteString("\t})\n}\n")

	source.WriteString("\nfunc assemble(ctx context.Context, input app.AssembleInput")
	for index := range modules {
		fmt.Fprintf(source, ", identity%d module.Identity", index)
	}
	source.WriteString(") (*app.Assembly, error) {\n")
	source.WriteString("\tassembly := app.NewAssembly()\n")
	source.WriteString("\tinfrastructure, err := generatedInfrastructureConfig(ctx, input.RootSource())\n")
	source.WriteString("\tif err != nil {\n\t\treturn assembly, err\n\t}\n")
	if hasProducers || hasConsumers {
		source.WriteString("\tif !infrastructure.Cool.Outbox.Enabled {\n")
		source.WriteString("\t\treturn assembly, exception.Core(\"应用存在 Producer 或 Consumer，不能关闭 Outbox\")\n\t}\n")
	}

	for index, current := range modules {
		configAlias := imports.alias(current.config.packagePath)
		fmt.Fprintf(source, "\tconfig%d, err := module.Compile(ctx, identity%d, %s.ModuleConfig(), input.ModuleDefaultsSource())\n", index, index, configAlias)
		source.WriteString("\tif err != nil {\n\t\treturn assembly, err\n\t}\n")
		configUsed := false
		for _, dependency := range dependencies {
			if dependency.provider.kind == ProviderKindConfig && dependency.provider.module == current.key {
				configUsed = true
				break
			}
		}
		if !configUsed {
			fmt.Fprintf(source, "\t_ = config%d\n", index)
		}
	}
	usedProviders := make(map[string]bool)
	for _, dependency := range dependencies {
		usedProviders[renderProviderKey(dependency.provider)] = true
	}
	for _, fragment := range fragments {
		name := generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity)
		fmt.Fprintf(source, "\tdescriptor_%s := %s()\n", name, descriptorFunctionName(fragment))
	}
	if len(fragments) > 0 || hasProducers || hasConsumers || len(controllers) > 0 || hasSeedModules(modules) {
		source.WriteString("\truntime, recycler, err := generatedDataRuntime(ctx, infrastructure")
		for _, fragment := range fragments {
			fmt.Fprintf(source, ", descriptor_%s", generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity))
		}
		source.WriteString(")\n")
		source.WriteString("\tif err != nil {\n\t\treturn assembly, err\n\t}\n")
		source.WriteString("\t_ = runtime\n\t_ = recycler\n")
		if hasAuthProviders(graph.Providers()) {
			fmt.Fprintf(source, "\tassembly.AddComponent(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, app.Hooks{})\n", frameworkModuleKey, authPackagePath, "Service")
			fmt.Fprintf(source, "\tassembly.AddComponent(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, app.Hooks{})\n", frameworkModuleKey, authPackagePath, "Store")
		}
		if hasFrameworkProvider(graph.Providers(), authBcryptPackagePath, "Verifier") {
			fmt.Fprintf(source, "\tassembly.AddComponent(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, app.Hooks{})\n", frameworkModuleKey, authBcryptPackagePath, "Verifier")
		}
		fmt.Fprintf(source, "\tassembly.AddComponent(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, app.Hooks{})\n", frameworkModuleKey, databasePackagePath, "Runtime")
	}
	if hasSeedModules(modules) {
		source.WriteString("\tseedRuntime, err := seed.NewRuntime(runtime,\n")
		for _, current := range modules {
			if !current.seedDB && !current.seedMenu {
				continue
			}
			db, menu := "nil", "nil"
			if current.seedDB {
				db = "seedDB_" + generatedIdentifier(current.key)
			}
			if current.seedMenu {
				menu = "seedMenu_" + generatedIdentifier(current.key)
			}
			fmt.Fprintf(source, "\t\tseed.NewDefinition(%q, seed.NewData(%s, %s)", current.key, db, menu)
			for _, fragment := range fragments {
				if fragment.module == current.key {
					fmt.Fprintf(source, ", descriptor_%s", generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity))
				}
			}
			source.WriteString("),\n")
		}
		source.WriteString("\t)\n")
		source.WriteString("\tif err != nil { return assembly, exception.WrapCore(err, \"构造种子运行时失败\") }\n")
		source.WriteString("\tif err = seedRuntime.OnInit(ctx); err != nil { return assembly, exception.WrapCore(err, \"导入模块种子失败\") }\n")
	}
	if hasProducers || hasConsumers {
		source.WriteString("\toutboxStore, err := outboxstore.New(runtime)\n")
		source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 Outbox Store 失败\")\n\t}\n")
	}
	if hasProducers {
		source.WriteString("\tenqueuer, err := outbox.NewEnqueuer(runtime, outboxStore, infrastructure.Cool.Outbox.EnqueueLimits())\n")
		source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 Outbox Enqueuer 失败\")\n\t}\n")
	}
	for _, fragment := range fragments {
		name := generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity)
		if usedProviders[renderProviderKey(Provider{kind: ProviderKindBase, module: fragment.baseProvider.module, packagePath: fragment.entityPackage, name: fragment.baseProvider.name, typ: fragment.baseProvider.typ})] {
			fmt.Fprintf(source, "\tbase_%s, err := %s(descriptor_%s, runtime, recycler)\n", name, fragment.baseProvider.name, name)
			source.WriteString("\tif err != nil {\n\t\treturn assembly, err\n\t}\n")
		} else {
			fmt.Fprintf(source, "\tvar base_%s *coreservice.Base[%s.%s, uint64]\n", name, imports.alias(fragment.entityPackage), fragment.entity)
			fmt.Fprintf(source, "\t_ = base_%s\n", name)
		}
	}
	if hasAuthProviders(graph.Providers()) {
		source.WriteString("\tjwtService, err := auth.NewJWT(infrastructure.Cool.Auth.JWT)\n")
		source.WriteString("\tif err != nil { return assembly, exception.WrapCore(err, \"构造 JWT 服务失败\") }\n")
		source.WriteString("\tsessionAdapter, err := auth.NewSessionStore(ctx, infrastructure.Cool.Auth.Session)\n")
		source.WriteString("\tif err != nil { return assembly, exception.WrapCore(err, \"构造 Session Store 失败\") }\n")
		authorizer, exists := authorizerComponent(components)
		if exists {
			for _, prerequisite := range authorizerPrerequisites(authorizer, components, dependencies) {
				writeComponentConstruction(source, prerequisite, dependencies, modules, fragments, descriptorProviders, components, componentResultRequired(prerequisite, graph, dependencies, modules, controllers, components), imports)
			}
		}
		authorizerValue := "nil"
		if exists {
			authorizerValue = componentVariableName(authorizer.component)
		}
		fmt.Fprintf(source, "\tauthService, err := auth.NewService(jwtService, sessionAdapter, %s)\n", authorizerValue)
		source.WriteString("\tif err != nil { return assembly, exception.WrapCore(err, \"构造 Auth 服务失败\") }\n")
	}
	if hasFrameworkProvider(graph.Providers(), authBcryptPackagePath, "Verifier") {
		source.WriteString("\tbcryptVerifier, err := authbcrypt.New(authbcrypt.Config{})\n")
		source.WriteString("\tif err != nil { return assembly, exception.WrapCore(err, \"构造 bcrypt 验证器失败\") }\n")
	}
	for _, current := range components {
		if authorizer, exists := authorizerComponent(components); exists && authorizerDependency(authorizer, current, components, dependencies) {
			continue
		}
		writeComponentConstruction(source, current, dependencies, modules, fragments, descriptorProviders, components, componentResultRequired(current, graph, dependencies, modules, controllers, components), imports)
	}
	for _, current := range controllers {
		arguments := make([]string, len(current.declaration.parameterTypes))
		for index, parameter := range current.declaration.parameterTypes {
			arguments[index], _ = componentExpressionForType(parameter, components)
		}
		name := "controller_" + generatedIdentifier(current.module, current.declaration.packagePath, current.declaration.name)
		fmt.Fprintf(source, "\t%s := %s(%s)\n", name, controllerFunctionName(current), strings.Join(arguments, ", "))
	}
	writeEPSPublish(source, controllers, fragments)
	writeHTTPInstallerClosure(source, modules, fragments, services, controllers, components, imports, hasAuthProviders(graph.Providers()))
	source.WriteString("\thttpTransport, err := apphttp.New(infrastructure.Cool.Transports.HTTP, generatedHTTPInstaller)\n")
	source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 HTTP Transport 失败\")\n\t}\n")
	fmt.Fprintf(source, "\tassembly.AddTransport(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: \"New\"}, httpTransport, app.Hooks{})\n", frameworkModuleKey, appHTTPPackagePath)
	source.WriteString("\tgrpcTransport, err := coolgrpc.New(infrastructure.Cool.Transports.GRPC, GRPCRegistrar(), nil, nil)\n")
	source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 gRPC Transport 失败\")\n\t}\n")
	fmt.Fprintf(source, "\tassembly.AddTransport(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: \"New\"}, grpcTransport, app.Hooks{})\n", frameworkModuleKey, grpcPackagePath)
	if hasProducers {
		publisherExpression := componentVariableName(publisher)
		fmt.Fprintf(source, "\toutboxWorker, err := outbox.NewWorker(outboxStore, %s, infrastructure.Cool.Outbox.WorkerConfig(), nil, nil)\n", publisherExpression)
		source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 Outbox Worker 失败\")\n\t}\n")
		fmt.Fprintf(source, "\tassembly.AddComponent(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, app.Hooks{Starter: outboxWorker, Stopper: outboxWorker, Supervisor: outboxWorker})\n", workerDefinition.module, workerDefinition.packagePath, workerDefinition.name)
	}
	if hasConsumers {
		definitions := make([]string, len(consumers))
		for index, consumer := range consumers {
			definitions[index] = componentVariableName(consumer)
		}
		fmt.Fprintf(source, "\toutboxDeliverer, err := outbox.NewDeliverer(runtime, outboxStore, infrastructure.Cool.Outbox.ConsumerConfig(), %s)\n", strings.Join(definitions, ", "))
		source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 Outbox Deliverer 失败\")\n\t}\n")
		fmt.Fprintf(source, "\toutboxConsumerRuntime, err := outbox.NewConsumerRuntime(%s, outboxStore, outboxDeliverer)\n", componentVariableName(consumerAdapter))
		source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 Consumer Runtime 失败\")\n\t}\n")
		fmt.Fprintf(source, "\tassembly.AddComponent(module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}, app.Hooks{Initializer: outboxConsumerRuntime, Starter: outboxConsumerRuntime, Stopper: outboxConsumerRuntime, Supervisor: outboxConsumerRuntime})\n", consumerRuntimeDefinition.module, consumerRuntimeDefinition.packagePath, consumerRuntimeDefinition.name)
	}
	source.WriteString("\treturn assembly, nil\n}\n")
	source.WriteString("\nfunc Generated() app.Definition {\n\tgraph := generatedGraph()\n\treturn app.Define(graph, func(ctx context.Context, input app.AssembleInput) (*app.Assembly, error) {\n\t\treturn assemble(ctx, input")
	for index := range modules {
		fmt.Fprintf(source, ", graph.Modules()[%d].Identity()", index)
	}
	source.WriteString(")\n\t})\n}\n")
}

func hasSeedModules(modules []renderModule) bool {
	for _, current := range modules {
		if current.seedDB || current.seedMenu {
			return true
		}
	}
	return false
}

func componentExpressionForType(parameter types.Type, components []renderComponent) (string, bool) {
	var expression string
	for _, current := range components {
		if types.AssignableTo(current.constructor.resultType, parameter) {
			if expression != "" {
				return "", false
			}
			expression = componentVariableName(current.component)
		}
	}
	return expression, expression != ""
}

func writeEPSPublish(source *strings.Builder, controllers []renderController, fragments []DescriptorFragment) {
	if len(controllers) == 0 {
		return
	}
	source.WriteString("\tepsViews, err := eps.CompileViews(eps.Input{\n")
	source.WriteString("\t\tGraph: generatedGraph(),\n")
	source.WriteString("\t\tControllers: []eps.ControllerInput{\n")
	for _, controller := range controllers {
		fmt.Fprintf(
			source,
			"\t\t\t{Key: %q, Definition: controller_%s},\n",
			controllerKey(controller),
			generatedIdentifier(controller.module, controller.declaration.packagePath, controller.declaration.name),
		)
	}
	source.WriteString("\t\t},\n")
	source.WriteString("\t\tDescriptors: []coreentity.RuntimeDescriptor{\n")
	for _, fragment := range fragments {
		fmt.Fprintf(
			source,
			"\t\t\tdescriptor_%s,\n",
			generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity),
		)
	}
	source.WriteString("\t\t},\n")
	source.WriteString("\t}, gmode.IsDevelop())\n")
	source.WriteString("\tif err != nil { return assembly, exception.WrapCore(err, \"编译 EPS 视图失败\") }\n")
	source.WriteString("\tif err = eps.PublishViews(epsViews); err != nil { return assembly, exception.WrapCore(err, \"发布 EPS 视图失败\") }\n")
}

func writeComponentConstruction(source *strings.Builder, current renderComponent, dependencies []Dependency, modules []renderModule, fragments []DescriptorFragment, descriptorProviders map[string]Provider, components []renderComponent, resultRequired bool, imports *importManager) {
	componentName := componentVariableName(current.component)
	currentDependencies := componentDependencies(current.component, dependencies)
	arguments := make([]string, len(currentDependencies))
	for index, dependency := range currentDependencies {
		arguments[index], _ = providerExpression(dependency.provider, modules, fragments, descriptorProviders, components)
	}
	call := imports.alias(current.constructor.packagePath) + "." + current.constructor.name + "(" + strings.Join(arguments, ", ") + ")"
	errorMessage := "构造组件 " + current.component.packagePath + "." + current.component.name + " 失败"
	switch {
	case resultRequired && constructorReturnsError(current.constructor):
		fmt.Fprintf(source, "\t%s, err := %s\n", componentName, call)
		fmt.Fprintf(source, "\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, %q)\n\t}\n", errorMessage)
	case resultRequired:
		fmt.Fprintf(source, "\t%s := %s\n", componentName, call)
	case constructorReturnsError(current.constructor):
		fmt.Fprintf(source, "\tif _, err := %s; err != nil {\n\t\treturn assembly, exception.WrapCore(err, %q)\n\t}\n", call, errorMessage)
	default:
		fmt.Fprintf(source, "\t%s\n", call)
	}
	hooksName := "hooks_" + generatedIdentifier(current.component.module, current.component.packagePath, current.component.name)
	fmt.Fprintf(source, "\t%s := app.Hooks{}\n", hooksName)
	if current.constructor.hasInitializer {
		fmt.Fprintf(source, "\t%s.Initializer = %s\n", hooksName, componentName)
	}
	if current.constructor.hasStarter {
		fmt.Fprintf(source, "\t%s.Starter = %s\n", hooksName, componentName)
	}
	if current.constructor.hasStopper {
		fmt.Fprintf(source, "\t%s.Stopper = %s\n", hooksName, componentName)
	}
	definitionName := "definition_" + generatedIdentifier(current.component.module, current.component.packagePath, current.component.name)
	fmt.Fprintf(source, "\t%s := module.ComponentDefinition{Module: %q, PackagePath: %q, Name: %q}\n", definitionName, current.component.module, current.component.packagePath, current.component.name)
	if current.constructor.hasTransport {
		transportName := "transport_" + generatedIdentifier(current.component.module, current.component.packagePath, current.component.name)
		fmt.Fprintf(source, "\tvar %s app.Transport = %s\n", transportName, componentName)
		fmt.Fprintf(source, "\tassembly.AddTransport(%s, %s, %s)\n", definitionName, transportName, hooksName)
	} else {
		fmt.Fprintf(source, "\tassembly.AddComponent(%s, %s)\n", definitionName, hooksName)
	}
}

func componentResultRequired(current renderComponent, graph *Graph, dependencies []Dependency, modules []renderModule, controllers []renderController, components []renderComponent) bool {
	constructor := current.constructor
	if constructor.hasInitializer || constructor.hasStarter || constructor.hasStopper || constructor.hasTransport ||
		constructor.isConsumerDefinition || constructor.isPublisher || constructor.isConsumerAdapter {
		return true
	}
	for _, dependency := range dependencies {
		provider := dependency.provider
		if (provider.kind == ProviderKindComponent || provider.kind == ProviderKindConsumerDefinition) &&
			provider.module == current.component.module && provider.packagePath == current.component.packagePath && provider.name == current.component.name {
			return true
		}
	}
	if hasAuthProviders(graph.Providers()) {
		if authorizer, exists := authorizerComponent(components); exists && sameComponent(authorizer.component, current.component) {
			return true
		}
	} else if len(controllers) > 0 && implementsHTTPAuthenticator(constructor.resultType) {
		return true
	}
	for _, controller := range controllers {
		for _, parameter := range controller.declaration.parameterTypes {
			if types.AssignableTo(constructor.resultType, parameter) {
				return true
			}
		}
		for _, reference := range modulesReferences(controller.module, modules) {
			if component, exists := middlewareComponent(controller.module, reference.symbol, modules, components); exists && sameComponent(component.component, current.component) {
				return true
			}
		}
		for _, symbol := range controller.declaration.middleware {
			if component, exists := middlewareComponent(controller.module, symbol, modules, components); exists && sameComponent(component.component, current.component) {
				return true
			}
		}
		for _, route := range controller.declaration.routes {
			if route.kind == coreroute.KindCRUD {
				if component, exists := componentForType(controller.declaration.serviceType, components); exists && sameComponent(component.component, current.component) {
					return true
				}
			} else if !isPackageHandler(route.handler) {
				if component, exists := handlerComponent(route.handler, components); exists && sameComponent(component.component, current.component) {
					return true
				}
			}
			for _, symbol := range route.middleware {
				if component, exists := middlewareComponent(controller.module, symbol, modules, components); exists && sameComponent(component.component, current.component) {
					return true
				}
			}
		}
	}

	return false
}

func modulesReferences(moduleKey string, modules []renderModule) []Reference {
	for _, current := range modules {
		if current.key == moduleKey {
			return current.references
		}
	}

	return nil
}

func sameComponent(left, right Component) bool {
	return left.module == right.module && left.packagePath == right.packagePath && left.name == right.name
}

func authorizerComponent(components []renderComponent) (renderComponent, bool) {
	for _, component := range components {
		method := types.NewMethodSet(types.Unalias(component.constructor.resultType)).Lookup(nil, "Authorize")
		if method == nil {
			continue
		}
		signature, ok := method.Obj().Type().(*types.Signature)
		if ok && signature.Params().Len() == 2 && signature.Results().Len() == 2 &&
			isContextType(signature.Params().At(0).Type()) && types.Identical(signature.Results().At(0).Type(), types.Typ[types.Bool]) &&
			types.Identical(signature.Results().At(1).Type(), types.Universe.Lookup("error").Type()) {
			return component, true
		}
	}
	return renderComponent{}, false
}

func authorizerPrerequisites(authorizer renderComponent, components []renderComponent, dependencies []Dependency) []renderComponent {
	var result []renderComponent
	for _, component := range components {
		if authorizerDependency(authorizer, component, components, dependencies) {
			result = append(result, component)
		}
	}
	return result
}

func authorizerDependency(authorizer, candidate renderComponent, components []renderComponent, dependencies []Dependency) bool {
	needed := map[string]bool{componentVariableName(authorizer.component): true}
	changed := true
	for changed {
		changed = false
		for _, dependency := range dependencies {
			if !needed[componentVariableName(dependency.consumer)] {
				continue
			}
			for _, component := range components {
				if component.component.module == dependency.provider.module && component.component.packagePath == dependency.provider.packagePath && component.component.name == dependency.provider.name {
					key := componentVariableName(component.component)
					if !needed[key] {
						needed[key] = true
						changed = true
					}
				}
			}
		}
	}
	return needed[componentVariableName(candidate.component)]
}

func validateControllerDependencies(controllers []renderController, components []renderComponent) error {
	for _, controller := range controllers {
		for index, parameter := range controller.declaration.parameterTypes {
			matches := 0
			for _, component := range components {
				if types.AssignableTo(component.constructor.resultType, parameter) {
					matches++
				}
			}
			if matches == 0 {
				return renderError("CG098", fmt.Sprintf("Controller %s 的第 %d 个参数缺少可构造组件", controller.declaration.name, index+1), controller.declaration.position)
			}
			if matches > 1 {
				return renderError("CG098", fmt.Sprintf("Controller %s 的第 %d 个参数匹配多个组件", controller.declaration.name, index+1), controller.declaration.position)
			}
		}
	}
	return nil
}

func componentVariableName(component Component) string {
	return "component_" + generatedIdentifier(component.module, component.packagePath, component.name)
}

func providerExpression(provider Provider, modules []renderModule, fragments []DescriptorFragment, descriptorProviders map[string]Provider, components []renderComponent) (string, bool) {
	switch provider.kind {
	case ProviderKindConfig:
		for index, current := range modules {
			if current.key == provider.module {
				return fmt.Sprintf("config%d.Config()", index), true
			}
		}
	case ProviderKindSeed:
		for _, current := range modules {
			if current.key == provider.module {
				db, menu := "nil", "nil"
				if current.seedDB {
					db = "seedDB_" + generatedIdentifier(current.key)
				}
				if current.seedMenu {
					menu = "seedMenu_" + generatedIdentifier(current.key)
				}
				return fmt.Sprintf("seed.NewData(%s, %s)", db, menu), true
			}
		}
	case ProviderKindDescriptor:
		for _, fragment := range fragments {
			key := descriptorKey(fragment.module, fragment.entityPackage, fragment.entity)
			if descriptorProviders[key] == provider {
				return "descriptor_" + generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity), true
			}
		}
	case ProviderKindBase:
		for _, fragment := range fragments {
			if fragment.baseProvider.module == provider.module && fragment.baseProvider.name == provider.name {
				return "base_" + generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity), true
			}
		}
	case ProviderKindComponent, ProviderKindConsumerDefinition:
		for _, current := range components {
			if current.component.module == provider.module && current.component.packagePath == provider.packagePath && current.component.name == provider.name {
				return componentVariableName(current.component), true
			}
		}
		// 框架非构造器 Provider（如数据库 Runtime）使用局部变量名
		if provider.module == frameworkModuleKey && provider.packagePath == databasePackagePath && provider.name == "Runtime" {
			return "runtime", true
		}
		if provider.module == frameworkModuleKey && provider.packagePath == authPackagePath {
			switch provider.name {
			case "Service":
				return "authService", true
			case "Codec":
				return "jwtService", true
			case "Store":
				return "sessionAdapter", true
			}
		}
		if provider.module == frameworkModuleKey && provider.packagePath == authBcryptPackagePath && provider.name == "Verifier" {
			return "bcryptVerifier", true
		}
	case ProviderKindEnqueuer:
		return "enqueuer", true
	}
	return "", false
}

func hasAuthProviders(providers []Provider) bool {
	for _, provider := range providers {
		if provider.module == frameworkModuleKey && provider.packagePath == authPackagePath {
			return true
		}
	}
	return false
}

func hasFrameworkProvider(providers []Provider, packagePath, name string) bool {
	for _, provider := range providers {
		if provider.module == frameworkModuleKey && provider.packagePath == packagePath && provider.name == name {
			return true
		}
	}
	return false
}

func validateProviderExpressions(dependencies []Dependency, modules []renderModule, fragments []DescriptorFragment, descriptorProviders map[string]Provider, components []renderComponent) error {
	for _, dependency := range dependencies {
		if _, ok := providerExpression(dependency.provider, modules, fragments, descriptorProviders, components); !ok {
			return renderError("CG088", "Provider 无法映射到静态装配局部变量", dependency.position)
		}
	}
	return nil
}

func writeControllerDefinition(source *strings.Builder, current renderController) {
	declaration := current.declaration
	fmt.Fprintf(
		source,
		"\t\t\t{Key: %q, Module: %q, Path: %q, Sensitive: %t, IgnoreGlobalPrefix: %t, DevelopmentOnly: %t, Description: %q, TagName: %q, Factory: ",
		controllerKey(current),
		current.module,
		declaration.path,
		declaration.sensitive,
		declaration.ignoreGlobalPrefix,
		declaration.developmentOnly,
		declaration.description,
		declaration.tagName,
	)
	writeCallableReference(source, corerouteFactoryReference(declaration))
	writeStringField(source, "Alias", declaration.aliases)
	writeStringField(source, "Middleware", declaration.middleware)
	source.WriteString("},\n")
}

func writeRouteDefinition(source *strings.Builder, controller renderController, route RouteDeclaration) {
	fmt.Fprintf(
		source,
		"\t\t\t{Controller: %q, Kind: coreroute.Kind%s, Method: %q, Path: %q, Summary: %q, Description: %q, DevelopmentOnly: %t, Bind: coreroute.Bind%s, Handler: ",
		controllerKey(controller),
		routeKindName(route.kind),
		route.method,
		route.path,
		route.summary,
		route.description,
		route.developmentOnly,
		bindSourceName(route.bind),
	)
	writeCallableReference(source, route.handler)
	writeStringField(source, "Middleware", route.middleware)
	writeStringField(source, "Tags", route.tags)
	if route.transaction.IsNonTransactional() {
		source.WriteString(", Transaction: coreroute.NonTransactional()")
	}
	source.WriteString("},\n")
}

func writeCallableReference(source *strings.Builder, reference coreroute.CallableRef) {
	fmt.Fprintf(
		source,
		"coreroute.CallableRef{PackagePath: %q, Symbol: %q, Method: %q, Type: %q, HasRequest: %t, RequestPackagePath: %q, RequestType: %q, ReturnsValue: %t}",
		reference.PackagePath,
		reference.Symbol,
		reference.Method,
		reference.Type,
		reference.HasRequest,
		reference.RequestPackagePath,
		reference.RequestType,
		reference.ReturnsValue,
	)
}

func validateHTTPDependencies(
	modules []renderModule,
	fragments []DescriptorFragment,
	services []renderService,
	controllers []renderController,
	components []renderComponent,
	hasFrameworkAuth bool,
) error {
	if len(controllers) == 0 {
		return nil
	}
	authenticators := 0
	if hasFrameworkAuth {
		authenticators++
	}
	for _, component := range components {
		if implementsHTTPAuthenticator(component.constructor.resultType) {
			authenticators++
		}
	}
	if authenticators != 1 {
		return renderError("CG105", "HTTP 路由必须匹配唯一 Authenticator 组件", controllers[0].declaration.position)
	}
	for _, current := range modules {
		for _, reference := range current.references {
			if _, exists := middlewareComponent(current.key, reference.symbol, modules, components); !exists {
				return renderError("CG106", "HTTP 中间件缺少可构造组件或未实现 Handle", reference.position)
			}
		}
	}
	for _, current := range controllers {
		for _, symbol := range current.declaration.middleware {
			if _, exists := middlewareComponent(current.module, symbol, modules, components); !exists {
				return renderError("CG106", "Controller 中间件缺少可构造组件或未实现 Handle", current.declaration.position)
			}
		}
		for _, route := range current.declaration.routes {
			for _, symbol := range route.middleware {
				if _, exists := middlewareComponent(current.module, symbol, modules, components); !exists {
					return renderError("CG106", "Route 中间件缺少可构造组件或未实现 Handle", route.position)
				}
			}
			if route.kind == coreroute.KindCRUD {
				_, serviceExists := renderServiceForController(current, services)
				_, componentExists := componentForType(current.declaration.serviceType, components)
				_, descriptorExists := descriptorForType(current.declaration.entityType, fragments)
				if !serviceExists || !componentExists || !descriptorExists {
					return renderError("CG107", "CRUD 路由缺少 Service 组件或 Descriptor", route.position)
				}
				continue
			}
			if !isPackageHandler(route.handler) {
				if _, exists := handlerComponent(route.handler, components); !exists {
					return renderError("CG108", "自定义 Route Handler 缺少可构造接收者", route.position)
				}
			}
		}
	}

	return nil
}

func implementsHTTPAuthenticator(value types.Type) bool {
	selection := types.NewMethodSet(types.Unalias(value)).Lookup(nil, "AuthenticateHTTP")
	if selection == nil {
		return false
	}
	signature, matches := selection.Obj().Type().(*types.Signature)
	if !matches || signature.Params().Len() != 6 || signature.Results().Len() != 2 ||
		!isContextType(signature.Params().At(0).Type()) ||
		!types.Identical(signature.Params().At(5).Type(), types.Typ[types.Bool]) ||
		!isContextType(signature.Results().At(0).Type()) ||
		!types.Identical(signature.Results().At(1).Type(), types.Universe.Lookup("error").Type()) {
		return false
	}
	for index := 1; index < 5; index++ {
		if !types.Identical(signature.Params().At(index).Type(), types.Typ[types.String]) {
			return false
		}
	}

	return true
}

func implementsHTTPMiddleware(value types.Type) bool {
	selection := types.NewMethodSet(types.Unalias(value)).Lookup(nil, "Handle")
	if selection == nil {
		return false
	}
	signature, matches := selection.Obj().Type().(*types.Signature)
	if !matches || signature.Params().Len() != 1 || signature.Results().Len() != 0 {
		return false
	}
	pointer, matches := types.Unalias(signature.Params().At(0).Type()).(*types.Pointer)
	if !matches {
		return false
	}
	named, matches := types.Unalias(pointer.Elem()).(*types.Named)

	return matches && named.Obj() != nil && named.Obj().Pkg() != nil &&
		named.Obj().Pkg().Path() == ghttpPackagePath && named.Obj().Name() == "Request"
}

func middlewareComponent(moduleKey, symbol string, modules []renderModule, components []renderComponent) (renderComponent, bool) {
	var packagePath string
	for _, current := range modules {
		if current.key == moduleKey {
			parts := strings.Split(symbol, ".")
			if len(parts) < 2 {
				return renderComponent{}, false
			}
			packagePath = current.config.packagePath + "/" + strings.Join(parts[:len(parts)-1], "/")
			symbol = parts[len(parts)-1]
			break
		}
	}
	for _, component := range components {
		if component.component.module == moduleKey && component.component.packagePath == packagePath &&
			component.component.name == symbol && implementsHTTPMiddleware(component.constructor.resultType) {
			return component, true
		}
	}

	return renderComponent{}, false
}

func componentForType(target types.Type, components []renderComponent) (renderComponent, bool) {
	for _, component := range components {
		if types.AssignableTo(component.constructor.resultType, target) {
			return component, true
		}
	}

	return renderComponent{}, false
}

func handlerComponent(reference coreroute.CallableRef, components []renderComponent) (renderComponent, bool) {
	for _, component := range components {
		pointer, matches := types.Unalias(component.constructor.resultType).(*types.Pointer)
		if !matches {
			continue
		}
		named, matches := types.Unalias(pointer.Elem()).(*types.Named)
		if matches && named.Obj() != nil && named.Obj().Pkg() != nil &&
			named.Obj().Pkg().Path() == reference.PackagePath && named.Obj().Name() == reference.Symbol {
			return component, true
		}
	}

	return renderComponent{}, false
}

func renderServiceForController(controller renderController, services []renderService) (renderService, bool) {
	pointer, matches := types.Unalias(controller.declaration.serviceType).(*types.Pointer)
	if !matches {
		return renderService{}, false
	}
	target, matches := types.Unalias(pointer.Elem()).(*types.Named)
	if !matches {
		return renderService{}, false
	}
	for _, service := range services {
		if service.declaration.typ != nil && types.Identical(service.declaration.typ, target) {
			return service, true
		}
	}

	return renderService{}, false
}

func descriptorForType(target types.Type, fragments []DescriptorFragment) (DescriptorFragment, bool) {
	for _, fragment := range fragments {
		if types.Identical(types.Unalias(fragment.entityType), types.Unalias(target)) {
			return fragment, true
		}
	}

	return DescriptorFragment{}, false
}

func isPackageHandler(reference coreroute.CallableRef) bool {
	return strings.HasPrefix(reference.Type, "func(")
}

func writeHTTPInstallerClosure(
	source *strings.Builder,
	modules []renderModule,
	fragments []DescriptorFragment,
	services []renderService,
	controllers []renderController,
	components []renderComponent,
	imports *importManager,
	hasFrameworkAuth bool,
) {
	if len(controllers) == 0 {
		source.WriteString("\tgeneratedHTTPInstaller := func(server *ghttp.Server) error {\n")
		source.WriteString("\t\tif server == nil {\n\t\t\treturn exception.Core(\"HTTP Server 未初始化\")\n\t\t}\n")
		source.WriteString("\t\treturn nil\n\t}\n")

		return
	}
	source.WriteString("\tbinder, err := corecontroller.NewBinder(infrastructure.Cool.CRUD)\n")
	source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 HTTP Binder 失败\")\n\t}\n")
	source.WriteString("\tdispatcher, err := crud.NewDispatcher(runtime.Runner())\n")
	source.WriteString("\tif err != nil {\n\t\treturn assembly, exception.WrapCore(err, \"构造 CRUD Dispatcher 失败\")\n\t}\n")
	source.WriteString("\tdescriptorResolver := corecontroller.DescriptorResolverFunc(func(value any) (coreentity.Metadata, bool) {\n")
	source.WriteString("\t\tswitch value.(type) {\n")
	for _, fragment := range fragments {
		fmt.Fprintf(
			source,
			"\t\tcase %s.%s:\n\t\t\treturn descriptor_%s, true\n",
			imports.alias(fragment.entityPackage),
			fragment.entity,
			generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity),
		)
	}
	source.WriteString("\t\tdefault:\n\t\t\treturn nil, false\n\t\t}\n\t})\n")
	authenticator := "authService"
	if !hasFrameworkAuth {
		authenticator = componentVariableName(httpAuthenticatorComponent(components).component)
	}
	source.WriteString("\tgeneratedHTTPInstaller := func(server *ghttp.Server) error {\n")
	source.WriteString("\t\tif server == nil {\n\t\t\treturn exception.Core(\"HTTP Server 未初始化\")\n\t\t}\n")
	source.WriteString("\t\tserver.Use(corecontroller.NewResponseMiddleware(nil))\n")
	for _, current := range modules {
		for _, reference := range current.references {
			if reference.group != "GlobalMiddlewares" {
				continue
			}
			component, _ := middlewareComponent(current.key, reference.symbol, modules, components)
			fmt.Fprintf(source, "\t\tserver.Use(%s.Handle)\n", componentVariableName(component.component))
		}
	}
	for _, controller := range controllers {
		for _, route := range controller.declaration.routes {
			writeHTTPRouteInstall(source, modules, fragments, services, controller, route, components, authenticator, imports)
		}
	}
	source.WriteString("\t\treturn nil\n\t}\n")
}

func httpAuthenticatorComponent(components []renderComponent) renderComponent {
	for _, component := range components {
		if implementsHTTPAuthenticator(component.constructor.resultType) {
			return component
		}
	}

	return renderComponent{}
}

func writeHTTPRouteInstall(
	source *strings.Builder,
	modules []renderModule,
	fragments []DescriptorFragment,
	services []renderService,
	controller renderController,
	route RouteDeclaration,
	components []renderComponent,
	authenticator string,
	imports *importManager,
) {
	indent := "\t\t"
	if route.developmentOnly {
		source.WriteString("\t\tif gmode.IsDevelop() {\n")
		indent = "\t\t\t"
	}
	pattern := route.method + ":" + route.path
	routeName := generatedIdentifier(controller.module, route.method, route.path)
	ignoreToken := slices.Contains(route.tags, "ignoreToken")
	fmt.Fprintf(
		source,
		"%scontextMiddleware_%s, err := apphttp.NewContextMiddleware(%s, %q, %t)\n",
		indent,
		routeName,
		authenticator,
		route.path,
		ignoreToken,
	)
	fmt.Fprintf(source, "%sif err != nil {\n%s\treturn exception.WrapCore(err, %q)\n%s}\n", indent, indent, "构造 HTTP 路由中间件失败: "+route.method+" "+route.path, indent)
	fmt.Fprintf(source, "%sserver.BindMiddleware(%q, contextMiddleware_%s)\n", indent, pattern, routeName)
	writeHTTPRouteMiddlewares(source, indent, pattern, controller, route, modules, components)
	fmt.Fprintf(source, "%sserver.BindHandler(%q, func(ctx context.Context, _ *corecontroller.HTTPRequest) (any, error) {\n", indent, pattern)
	writeHTTPHandlerCall(source, indent+"\t", fragments, services, controller, route, components, imports)
	fmt.Fprintf(source, "%s})\n", indent)
	if route.developmentOnly {
		source.WriteString("\t\t}\n")
	}
}

func writeHTTPRouteMiddlewares(
	source *strings.Builder,
	indent string,
	pattern string,
	controller renderController,
	route RouteDeclaration,
	modules []renderModule,
	components []renderComponent,
) {
	var middleware []string
	for _, current := range modules {
		if current.key != controller.module {
			continue
		}
		for _, reference := range current.references {
			if reference.group == "Middlewares" {
				component, _ := middlewareComponent(current.key, reference.symbol, modules, components)
				middleware = append(middleware, componentVariableName(component.component)+".Handle")
			}
		}
	}
	for _, symbol := range controller.declaration.middleware {
		component, _ := middlewareComponent(controller.module, symbol, modules, components)
		middleware = append(middleware, componentVariableName(component.component)+".Handle")
	}
	for _, symbol := range route.middleware {
		component, _ := middlewareComponent(controller.module, symbol, modules, components)
		middleware = append(middleware, componentVariableName(component.component)+".Handle")
	}
	if len(middleware) > 0 {
		fmt.Fprintf(source, "%sserver.BindMiddleware(%q, %s)\n", indent, pattern, strings.Join(middleware, ", "))
	}
}

func writeHTTPHandlerCall(
	source *strings.Builder,
	indent string,
	fragments []DescriptorFragment,
	services []renderService,
	controller renderController,
	route RouteDeclaration,
	components []renderComponent,
	imports *importManager,
) {
	if route.kind == coreroute.KindCustom {
		writeCustomHTTPHandlerCall(source, indent, route, components, imports)

		return
	}
	service, _ := renderServiceForController(controller, services)
	component, _ := componentForType(controller.declaration.serviceType, components)
	fragment, _ := descriptorForType(controller.declaration.entityType, fragments)
	componentName := componentVariableName(component.component)
	controllerName := "controller_" + generatedIdentifier(controller.module, controller.declaration.packagePath, controller.declaration.name)
	mode := serviceActionModeName(service, route.handler.Method)
	adapter := serviceActionAdapterName(service, route.handler.Method)
	descriptor := "descriptor_" + generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity)
	entityType := imports.alias(fragment.entityPackage) + "." + fragment.entity
	switch route.handler.Method {
	case "Add":
		fmt.Fprintf(source, "%sreturn corecontroller.HandleAdd[%s, uint64](ctx, binder, dispatcher, descriptorResolver, %s, %s, %s, func(scopeCtx context.Context, input coreservice.AddInput[%s]) (coreservice.AddResult[uint64], error) {\n", indent, entityType, controllerName, mode, descriptor, entityType)
		fmt.Fprintf(source, "%s\treturn %s(scopeCtx, %s, input)\n%s})\n", indent, adapter, componentName, indent)
	case "Delete":
		fmt.Fprintf(source, "%sreturn corecontroller.HandleDelete[%s, uint64](ctx, binder, dispatcher, descriptorResolver, %s, %s, %s, func(scopeCtx context.Context, input coreservice.DeleteInput[uint64]) error {\n", indent, entityType, controllerName, mode, descriptor)
		fmt.Fprintf(source, "%s\treturn %s(scopeCtx, %s, input)\n%s})\n", indent, adapter, componentName, indent)
	case "Update":
		fmt.Fprintf(source, "%sreturn corecontroller.HandleUpdate[%s, uint64](ctx, binder, dispatcher, descriptorResolver, %s, %s, %s, func(scopeCtx context.Context, input coreservice.UpdateInput[%s, uint64]) error {\n", indent, entityType, controllerName, mode, descriptor, entityType)
		fmt.Fprintf(source, "%s\treturn %s(scopeCtx, %s, input)\n%s})\n", indent, adapter, componentName, indent)
	case "Info":
		if route.handler.HasRequest {
			writeCRUDDTOCall(source, indent, route, controllerName, mode, adapter, componentName, imports)
			return
		}
		fmt.Fprintf(source, "%sreturn corecontroller.HandleInfo[uint64](ctx, binder, dispatcher, descriptorResolver, %s, %s, func(scopeCtx context.Context, input uint64) (any, error) {\n", indent, controllerName, mode)
		fmt.Fprintf(source, "%s\treturn %s(scopeCtx, %s, input)\n", indent, adapter, componentName)
		fmt.Fprintf(source, "%s})\n", indent)
	case "List", "Page":
		if route.handler.HasRequest {
			writeCRUDDTOCall(source, indent, route, controllerName, mode, adapter, componentName, imports)
			return
		}
		fmt.Fprintf(source, "%sreturn corecontroller.HandleQuery(ctx, binder, dispatcher, descriptorResolver, %s, crud.Action%s, %s, func(scopeCtx context.Context, input coreservice.Query) (any, error) {\n", indent, controllerName, route.handler.Method, mode)
		fmt.Fprintf(source, "%s\treturn %s(scopeCtx, %s, input)\n", indent, adapter, componentName)
		fmt.Fprintf(source, "%s})\n", indent)
	}
}

func writeCRUDDTOCall(source *strings.Builder, indent string, route RouteDeclaration, controllerName, mode, adapter, componentName string, imports *importManager) {
	dtoType := imports.alias(route.handler.RequestPackagePath) + "." + route.handler.RequestType
	fmt.Fprintf(source, "%sreturn corecontroller.HandleCRUDDTO[%s](ctx, binder, coreroute.Bind%s, dispatcher, descriptorResolver, %s, crud.Action%s, %s, func(scopeCtx context.Context, input *%s) (any, error) {\n", indent, dtoType, bindSourceName(route.bind), controllerName, route.handler.Method, mode, dtoType)
	fmt.Fprintf(source, "%s\treturn %s(scopeCtx, %s, input)\n", indent, adapter, componentName)
	fmt.Fprintf(source, "%s})\n", indent)
}

func writeCustomHTTPHandlerCall(source *strings.Builder, indent string, route RouteDeclaration, components []renderComponent, imports *importManager) {
	target := imports.alias(route.handler.PackagePath) + "." + route.handler.Method
	if !isPackageHandler(route.handler) {
		component, _ := handlerComponent(route.handler, components)
		target = componentVariableName(component.component) + "." + route.handler.Method
	}
	policy := "coreroute.TransactionPolicy{}"
	if route.transaction.IsNonTransactional() {
		policy = "coreroute.NonTransactional()"
	}
	if route.handler.HasRequest {
		dtoType := imports.alias(route.handler.RequestPackagePath) + "." + route.handler.RequestType
		fmt.Fprintf(source, "%sreturn corecontroller.HandleDTO[%s](ctx, binder, coreroute.Bind%s, runtime.Runner(), %s, func(scopeCtx context.Context, input *%s) (any, error) {\n", indent, dtoType, bindSourceName(route.bind), policy, dtoType)
		writeInvokeResult(source, indent+"\t", target+"(scopeCtx, input)", route.handler.ReturnsValue)
		fmt.Fprintf(source, "%s})\n", indent)

		return
	}
	fmt.Fprintf(source, "%sreturn corecontroller.HandleNoDTO(ctx, runtime.Runner(), %s, func(scopeCtx context.Context) (any, error) {\n", indent, policy)
	writeInvokeResult(source, indent+"\t", target+"(scopeCtx)", route.handler.ReturnsValue)
	fmt.Fprintf(source, "%s})\n", indent)
}

func writeInvokeResult(source *strings.Builder, indent, call string, returnsValue bool) {
	if returnsValue {
		fmt.Fprintf(source, "%sreturn %s\n", indent, call)

		return
	}
	fmt.Fprintf(source, "%serr := %s\n%sreturn nil, err\n", indent, call, indent)
}

func writeStringField(source *strings.Builder, field string, values []string) {
	if len(values) == 0 {
		return
	}
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	fmt.Fprintf(source, ", %s: []string{%s}", field, strings.Join(quoted, ", "))
}

func corerouteFactoryReference(declaration ControllerDeclaration) coreroute.CallableRef {
	parameters := make([]string, len(declaration.parameterTypes))
	for index, parameter := range declaration.parameterTypes {
		parameters[index] = types.TypeString(parameter, qualifier)
	}

	return coreroute.CallableRef{
		PackagePath: declaration.packagePath,
		Symbol:      declaration.name,
		Type:        "func(" + strings.Join(parameters, ", ") + ") " + controllerPackagePath + ".Definition",
	}
}

func controllerKey(current renderController) string {
	return current.module + ":" + current.declaration.packagePath + "." + current.declaration.name
}

func controllerFunctionName(current renderController) string {
	return "controller" + generatedIdentifier(current.module, current.declaration.packagePath, current.declaration.name)
}

func routeKindName(kind coreroute.Kind) string {
	if kind == coreroute.KindCRUD {
		return "CRUD"
	}

	return "Custom"
}

func bindSourceName(source coreroute.BindSource) string {
	switch source {
	case coreroute.BindJSON:
		return "JSON"
	case coreroute.BindQuery:
		return "Query"
	case coreroute.BindForm:
		return "Form"
	case coreroute.BindPath:
		return "Path"
	case coreroute.BindFile:
		return "File"
	default:
		return "Auto"
	}
}

func writeComponentDefinition(source *strings.Builder, component Component) {
	fmt.Fprintf(
		source,
		"\t\t\t{Module: %q, PackagePath: %q, Name: %q},\n",
		component.module,
		component.packagePath,
		component.name,
	)
}

func writeOutboxRoleDefinitions(source *strings.Builder, field string, components []Component) {
	if len(components) == 0 {
		return
	}
	fmt.Fprintf(source, "\t\t\t%s: []module.ComponentDefinition{\n", field)
	for _, component := range components {
		writeComponentDefinition(source, component)
	}
	source.WriteString("\t\t\t},\n")
}

func componentProvider(graph *Graph, component Component) Provider {
	for _, provider := range graph.providers {
		if provider.module == component.module && provider.packagePath == component.packagePath && provider.name == component.name &&
			(provider.kind == ProviderKindComponent || provider.kind == ProviderKindConsumerDefinition) {
			return provider
		}
	}
	return Provider{}
}

func appendProviderIfMissing(providers []Provider, provider Provider) []Provider {
	key := renderProviderKey(provider)
	for _, current := range providers {
		if renderProviderKey(current) == key {
			return providers
		}
	}

	return append(providers, provider)
}

func writeProviderDefinition(source *strings.Builder, provider Provider, qualified bool) {
	if qualified {
		source.WriteString("module.ProviderDefinition")
	}
	fmt.Fprintf(
		source,
		"{Kind: %s, Module: %q, PackagePath: %q, Name: %q, Type: %q}",
		moduleProviderKind(provider.kind),
		provider.module,
		provider.packagePath,
		provider.name,
		provider.typ,
	)
}

func writeReferences(source *strings.Builder, field string, references []Reference, imports *importManager) {
	var values []string
	for _, reference := range references {
		if (field == "Middlewares" && reference.group == "Middlewares") || (field == "GlobalMiddlewares" && reference.group == "GlobalMiddlewares") {
			values = append(values, strconv.Quote(reference.symbol))
		}
	}
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(source, ", %s: []%s.ComponentRef{%s}", field, imports.alias(modulePackagePath), strings.Join(values, ", "))
}

func importsQualifier(imports *importManager) types.Qualifier {
	return func(pkg *types.Package) string {
		if pkg == nil {
			return ""
		}
		return imports.alias(pkg.Path())
	}
}

func constructorReturnsError(constructor Constructor) bool {
	return constructor.hasError
}

func componentKey(module, packagePath, name string) string {
	return module + ":" + packagePath + ":" + name
}

func renderProviderKey(provider Provider) string {
	return string(provider.kind) + ":" + provider.module + ":" + provider.packagePath + ":" + provider.name
}

func moduleProviderKind(kind ProviderKind) string {
	switch kind {
	case ProviderKindConfig:
		return "module.ProviderKindConfig"
	case ProviderKindSeed:
		return "module.ProviderKindSeed"
	case ProviderKindComponent:
		return "module.ProviderKindComponent"
	case ProviderKindDescriptor:
		return "module.ProviderKindDescriptor"
	case ProviderKindBase:
		return "module.ProviderKindBase"
	case ProviderKindEnqueuer:
		return "module.ProviderKindEnqueuer"
	case ProviderKindConsumerDefinition:
		return "module.ProviderKindConsumerDefinition"
	default:
		return ""
	}
}

func descriptorKey(module, packagePath, name string) string {
	return module + ":" + packagePath + ":" + name
}

func sortedRenderKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func descriptorFunctionName(fragment DescriptorFragment) string {
	return "descriptor" + generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity)
}

func doValueTypeName(fragment DescriptorFragment) string {
	return "doValue" + generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity)
}

func compiledDescriptorTypeName(fragment DescriptorFragment) string {
	return "compiledDescriptor" + generatedIdentifier(fragment.module, fragment.entityPackage, fragment.entity)
}

func serviceActionModeName(service renderService, action string) string {
	return "mode" + generatedIdentifier(service.module, service.declaration.packagePath, service.declaration.name, action)
}

func serviceActionAdapterName(service renderService, action string) string {
	return "adapter" + generatedIdentifier(service.module, service.declaration.packagePath, service.declaration.name, action)
}

func serviceActionTarget(actions []ServiceAction, action string) string {
	for _, current := range actions {
		if current.name == action && current.mode != ServiceActionBase {
			return "instance." + action
		}
	}

	return "instance.Base." + action
}

func serviceActionModeConstant(mode ServiceActionMode) string {
	switch mode {
	case ServiceActionBase:
		return "Base"
	case ServiceActionOverride:
		return "Override"
	case ServiceActionDelegate:
		return "Delegate"
	default:
		return ""
	}
}

func renderError(code, message string, position Position) error {
	return &DiagnosticError{diagnostics: []Diagnostic{{Code: code, Message: message, Position: position}}}
}
