package codegen

import (
	"go/ast"
	"go/token"
	"go/types"

	"golang.org/x/tools/go/packages"
)

const (
	generatedFileName   = "module_gen.go"
	globalGeneratedFile = "modules_gen.go"
	generatedHeader     = "// Code generated by cool generate. DO NOT EDIT."
)

// ScanOptions 定义模块扫描参数。
type ScanOptions struct {
	Root    string
	Overlay map[string][]byte
}

// Project 保存项目与已扫描模块。
type Project struct {
	Root       string
	ModulePath string
	Modules    []DiscoveredModule
	// StaleGeneratedFiles 保存仅供事务清理的旧模块生成文件。
	StaleGeneratedFiles []string
}

// DiscoveredModule 保存单个业务模块的包信息。
type DiscoveredModule struct {
	Key      string
	Dir      string
	Packages []*packages.Package
}

// SourceFunction 保存已定位的导出函数。
type SourceFunction struct {
	Package *packages.Package
	File    *ast.File
	Decl    *ast.FuncDecl
	Path    string
	Pos     token.Position
}

// ComponentKind 表示生成器识别的组件类型。
type ComponentKind string

const (
	ComponentModel            ComponentKind = "model"
	ComponentConfig     ComponentKind = "module-config"
	ComponentProvider         ComponentKind = "provider"
	ComponentRuntime          ComponentKind = "runtime"
	ComponentController       ComponentKind = "controller"
	ComponentGlobalMiddleware ComponentKind = "global-middleware"
	ComponentMiddleware       ComponentKind = "middleware"
	ComponentHandler          ComponentKind = "handler"
)

// Component 表示经过类型校验的模块组件。
type Component struct {
	Kind       ComponentKind
	ModuleKey  string
	Package    *packages.Package
	Function   string
	ImportPath string
	Output     string
	OutputType types.Type
	Parameters []Parameter
	HasError   bool
	Position   token.Position
}

// Parameter 保存构造函数单个参数的类型信息。
type Parameter struct {
	Name string
	Type string
	Raw  types.Type
}

// Analysis 保存单模块分析结果。
type Analysis struct {
	Module      DiscoveredModule
	Declaration ModuleDeclaration
	Components  []Component
}
