//go:build !cool_generate

// Code generated by cool generate. DO NOT EDIT.

package modules

import (
	context "context"
	sync "sync"
	time "time"

	gdb "github.com/gogf/gf/v2/database/gdb"
	controller "github.com/toothdy/cool-admin-go-next/cool/controller"
	recycle "github.com/toothdy/cool-admin-go-next/cool/db/recycle"
	entity "github.com/toothdy/cool-admin-go-next/cool/entity"
	middleware "github.com/toothdy/cool-admin-go-next/cool/middleware"
	module "github.com/toothdy/cool-admin-go-next/cool/module"
	auth "github.com/toothdy/cool-admin-go-next/cool/security"
	task "github.com/toothdy/cool-admin-go-next/cool/task"
	base "github.com/toothdy/cool-admin-go-next/modules/base"
	admin "github.com/toothdy/cool-admin-go-next/modules/base/controller/admin"
	sys "github.com/toothdy/cool-admin-go-next/modules/base/controller/admin/sys"
	app "github.com/toothdy/cool-admin-go-next/modules/base/controller/app"
	sys2 "github.com/toothdy/cool-admin-go-next/modules/base/entity/sys"
	event "github.com/toothdy/cool-admin-go-next/modules/base/event"
	global "github.com/toothdy/cool-admin-go-next/modules/base/middleware/global"
	sys3 "github.com/toothdy/cool-admin-go-next/modules/base/service/sys"
	upload "github.com/toothdy/cool-admin-go-next/modules/base/service/upload"
	dict "github.com/toothdy/cool-admin-go-next/modules/dict"
	admin2 "github.com/toothdy/cool-admin-go-next/modules/dict/controller/admin"
	entity2 "github.com/toothdy/cool-admin-go-next/modules/dict/entity"
	service "github.com/toothdy/cool-admin-go-next/modules/dict/service"
	recycle2 "github.com/toothdy/cool-admin-go-next/modules/recycle"
	admin3 "github.com/toothdy/cool-admin-go-next/modules/recycle/controller/admin"
	entity3 "github.com/toothdy/cool-admin-go-next/modules/recycle/entity"
	event2 "github.com/toothdy/cool-admin-go-next/modules/recycle/event"
	schedule "github.com/toothdy/cool-admin-go-next/modules/recycle/schedule"
	service2 "github.com/toothdy/cool-admin-go-next/modules/recycle/service"
	task2 "github.com/toothdy/cool-admin-go-next/modules/task"
	admin4 "github.com/toothdy/cool-admin-go-next/modules/task/controller/admin"
	entity4 "github.com/toothdy/cool-admin-go-next/modules/task/entity"
	event3 "github.com/toothdy/cool-admin-go-next/modules/task/event"
	middleware2 "github.com/toothdy/cool-admin-go-next/modules/task/middleware"
	queue "github.com/toothdy/cool-admin-go-next/modules/task/queue"
	service3 "github.com/toothdy/cool-admin-go-next/modules/task/service"
)

type moduleDependencies struct {
	context            context.Context
	db                 gdb.DB
	authManager        *auth.Manager
	sessionStore       auth.SessionStore
	controllerProvider module.ControllerProvider
	uploadDirectory    module.UploadDirectory
	recycleManager     *recycle.Manager
	models             []entity.Definition
	taskHandlers       []task.HandlerDefinition
	middlewareDeps     module.MiddlewareDeps
	authOptions        module.AuthOptions
	i18nOptions        module.I18nOptions
	crudOptions        module.CRUDOptions
	redisDefault       module.RedisDefaultConfig
}

func runtimeDependencies(source module.RuntimeDeps) moduleDependencies {
	return moduleDependencies{context: source.Context, db: source.DB, recycleManager: source.Recycle, models: source.Models, taskHandlers: source.TaskHandlers, authOptions: source.AuthOptions, i18nOptions: source.I18nOptions, crudOptions: source.CRUDOptions, redisDefault: source.RedisDefault}
}

func controllerDependencies(source module.Deps) moduleDependencies {
	return moduleDependencies{context: source.Context, db: source.DB, authManager: source.AuthManager, sessionStore: source.SessionStore, controllerProvider: source.EPSProvider, uploadDirectory: source.UploadDirectory, recycleManager: source.Recycle, models: source.Models, authOptions: source.AuthOptions, i18nOptions: source.I18nOptions, crudOptions: source.CRUDOptions, redisDefault: source.RedisDefault}
}

func middlewareDependencies(source module.MiddlewareDeps) moduleDependencies {
	return moduleDependencies{context: source.Context, db: source.DB, authManager: source.AuthManager, sessionStore: source.SessionStore, recycleManager: source.Recycle, models: source.Models, middlewareDeps: source, authOptions: source.AuthOptions, i18nOptions: source.I18nOptions, crudOptions: source.CRUDOptions, redisDefault: source.RedisDefault}
}

type recycleAssembly struct {
	configOnce                sync.Once
	config                    recycle2.Config
	configErr                 error
	recycleDataModel          entity.Definition
	recycleItemModel          entity.Definition
	recycleNewStoreOnce       sync.Once
	recycleNewStore           *event2.Store
	recycleNewStoreErr        error
	recycleNewCatalogOnce     sync.Once
	recycleNewCatalog         *service2.Catalog
	recycleNewCatalogErr      error
	recycleNewManagerOnce     sync.Once
	recycleNewManager         *recycle.Manager
	recycleNewManagerErr      error
	recycleNewDataServiceOnce sync.Once
	recycleNewDataService     *service2.DataService
	recycleNewDataServiceErr  error
	recycleNewDataOnce        sync.Once
	recycleNewData            *schedule.Data
	recycleNewDataErr         error
}

type baseAssembly struct {
	configOnce                     sync.Once
	config                         base.Config
	configErr                      error
	baseNewEPSServiceOnce          sync.Once
	baseNewEPSService              *admin.EPSService
	baseNewEPSServiceErr           error
	baseBaseSysConfModel           entity.Definition
	baseBaseSysDepartmentModel     entity.Definition
	baseBaseSysLogModel            entity.Definition
	baseBaseSysMenuModel           entity.Definition
	baseBaseSysParamModel          entity.Definition
	baseBaseSysRoleModel           entity.Definition
	baseBaseSysRoleDepartmentModel entity.Definition
	baseBaseSysRoleMenuModel       entity.Definition
	baseBaseSysUserModel           entity.Definition
	baseBaseSysUserRoleModel       entity.Definition
	baseNewAuthServiceOnce         sync.Once
	baseNewAuthService             *sys3.BaseSysLoginService
	baseNewAuthServiceErr          error
	baseNewConfServiceOnce         sync.Once
	baseNewConfService             *sys3.ConfService
	baseNewConfServiceErr          error
	baseNewLogServiceOnce          sync.Once
	baseNewLogService              *sys3.LogService
	baseNewLogServiceErr           error
	baseNewLogOnce                 sync.Once
	baseNewLog                     *event.Log
	baseNewLogErr                  error
	baseNewPermissionServiceOnce   sync.Once
	baseNewPermissionService       *sys3.PermissionService
	baseNewPermissionServiceErr    error
	baseNewServiceOnce             sync.Once
	baseNewService                 *upload.Service
	baseNewServiceErr              error
	baseNewDepartmentServiceOnce   sync.Once
	baseNewDepartmentService       *sys3.DepartmentService
	baseNewDepartmentServiceErr    error
	baseNewMenuServiceOnce         sync.Once
	baseNewMenuService             *sys3.MenuService
	baseNewMenuServiceErr          error
	baseNewParamServiceOnce        sync.Once
	baseNewParamService            *sys3.ParamService
	baseNewParamServiceErr         error
	baseNewRoleServiceOnce         sync.Once
	baseNewRoleService             *sys3.RoleService
	baseNewRoleServiceErr          error
	baseNewUserServiceOnce         sync.Once
	baseNewUserService             *sys3.UserService
	baseNewUserServiceErr          error
}

type dictAssembly struct {
	configOnce                 sync.Once
	config                     dict.Config
	configErr                  error
	dictDictInfoModel          entity.Definition
	dictDictTypeModel          entity.Definition
	dictNewDictInfoServiceOnce sync.Once
	dictNewDictInfoService     *service.DictInfoService
	dictNewDictInfoServiceErr  error
	dictNewDictTypeServiceOnce sync.Once
	dictNewDictTypeService     *service.DictTypeService
	dictNewDictTypeServiceErr  error
}

type taskAssembly struct {
	configOnce             sync.Once
	config                 task2.Config
	configErr              error
	taskHandlers           []task.HandlerDefinition
	taskTaskInfoModel      entity.Definition
	taskTaskLogModel       entity.Definition
	taskNewRedisClientOnce sync.Once
	taskNewRedisClient     queue.RedisClient
	taskNewRedisClientErr  error
	taskNewLocationOnce    sync.Once
	taskNewLocation        *time.Location
	taskNewLocationErr     error
	taskNewCommOnce        sync.Once
	taskNewComm            *event3.Comm
	taskNewCommErr         error
}

type projectAssembly struct {
	recycle recycleAssembly
	base    baseAssembly
	dict    dictAssembly
	task    taskAssembly
}

func (a *recycleAssembly) configure(ctx context.Context) error {
	a.configOnce.Do(func() {
		declaration := recycle2.ModuleConfig()
		a.config, a.configErr = module.LoadConfig(ctx, "recycle", declaration.Defaults)
	})
	return a.configErr
}

func (a *baseAssembly) configure(ctx context.Context) error {
	a.configOnce.Do(func() {
		declaration := base.ModuleConfig()
		a.config, a.configErr = module.LoadConfig(ctx, "base", declaration.Defaults)
	})
	return a.configErr
}

func (a *dictAssembly) configure(ctx context.Context) error {
	a.configOnce.Do(func() {
		declaration := dict.ModuleConfig()
		a.config, a.configErr = module.LoadConfig(ctx, "dict", declaration.Defaults)
	})
	return a.configErr
}

func (a *taskAssembly) configure(ctx context.Context) error {
	a.configOnce.Do(func() {
		declaration := task2.ModuleConfig()
		a.config, a.configErr = module.LoadConfig(ctx, "task", declaration.Defaults)
	})
	return a.configErr
}

func (a *projectAssembly) getBaseNewEPSService(deps moduleDependencies) (*admin.EPSService, error) {
	a.base.baseNewEPSServiceOnce.Do(func() {
		a.base.baseNewEPSService = admin.NewEPSService(deps.controllerProvider)
	})
	return a.base.baseNewEPSService, a.base.baseNewEPSServiceErr
}

func (a *projectAssembly) getBaseNewAuthService(deps moduleDependencies) (*sys3.BaseSysLoginService, error) {
	a.base.baseNewAuthServiceOnce.Do(func() {
		a.base.baseNewAuthService = sys3.NewAuthService(deps.db, deps.authManager, deps.sessionStore, deps.authOptions)
	})
	return a.base.baseNewAuthService, a.base.baseNewAuthServiceErr
}

func (a *projectAssembly) getBaseNewConfService(deps moduleDependencies) (*sys3.ConfService, error) {
	a.base.baseNewConfServiceOnce.Do(func() {
		a.base.baseNewConfService = sys3.NewConfService(deps.db, a.base.baseBaseSysConfModel)
	})
	return a.base.baseNewConfService, a.base.baseNewConfServiceErr
}

func (a *projectAssembly) getBaseNewLogService(deps moduleDependencies) (*sys3.LogService, error) {
	a.base.baseNewLogServiceOnce.Do(func() {
		a.base.baseNewLogService = sys3.NewLogService(deps.db, a.base.baseBaseSysLogModel, a.base.baseBaseSysUserModel, a.base.baseBaseSysConfModel)
	})
	return a.base.baseNewLogService, a.base.baseNewLogServiceErr
}

func (a *projectAssembly) getBaseNewLog(deps moduleDependencies) (*event.Log, error) {
	a.base.baseNewLogOnce.Do(func() {
		logServiceBaseNewLog, err := a.getBaseNewLogService(deps)
		if err != nil {
			a.base.baseNewLogErr = err
			return
		}
		a.base.baseNewLog, a.base.baseNewLogErr = event.NewLog(logServiceBaseNewLog, a.base.config)
	})
	return a.base.baseNewLog, a.base.baseNewLogErr
}

func (a *projectAssembly) getBaseNewPermissionService(deps moduleDependencies) (*sys3.PermissionService, error) {
	a.base.baseNewPermissionServiceOnce.Do(func() {
		a.base.baseNewPermissionService = sys3.NewPermissionService(deps.db)
	})
	return a.base.baseNewPermissionService, a.base.baseNewPermissionServiceErr
}

func (a *projectAssembly) getBaseNewService(deps moduleDependencies) (*upload.Service, error) {
	a.base.baseNewServiceOnce.Do(func() {
		a.base.baseNewService = upload.NewService(deps.uploadDirectory)
	})
	return a.base.baseNewService, a.base.baseNewServiceErr
}

func (a *projectAssembly) getRecycleNewStore(deps moduleDependencies) (*event2.Store, error) {
	a.recycle.recycleNewStoreOnce.Do(func() {
		a.recycle.recycleNewStore, a.recycle.recycleNewStoreErr = event2.NewStore(deps.db, a.recycle.recycleDataModel, a.recycle.recycleItemModel)
	})
	return a.recycle.recycleNewStore, a.recycle.recycleNewStoreErr
}

func (a *projectAssembly) getRecycleNewCatalog(deps moduleDependencies) (*service2.Catalog, error) {
	a.recycle.recycleNewCatalogOnce.Do(func() {
		a.recycle.recycleNewCatalog, a.recycle.recycleNewCatalogErr = service2.NewCatalog(deps.models)
	})
	return a.recycle.recycleNewCatalog, a.recycle.recycleNewCatalogErr
}

func (a *projectAssembly) getRecycleNewManager(deps moduleDependencies) (*recycle.Manager, error) {
	a.recycle.recycleNewManagerOnce.Do(func() {
		storeRecycleNewManager, err := a.getRecycleNewStore(deps)
		if err != nil {
			a.recycle.recycleNewManagerErr = err
			return
		}
		catalogRecycleNewManager, err := a.getRecycleNewCatalog(deps)
		if err != nil {
			a.recycle.recycleNewManagerErr = err
			return
		}
		a.recycle.recycleNewManager, a.recycle.recycleNewManagerErr = service2.NewManager(deps.db, storeRecycleNewManager, catalogRecycleNewManager, deps.crudOptions)
	})
	return a.recycle.recycleNewManager, a.recycle.recycleNewManagerErr
}

func (a *projectAssembly) getBaseNewDepartmentService(deps moduleDependencies) (*sys3.DepartmentService, error) {
	a.base.baseNewDepartmentServiceOnce.Do(func() {
		recycleManagerBaseNewDepartmentService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.base.baseNewDepartmentServiceErr = err
			return
		}
		a.base.baseNewDepartmentService = sys3.NewDepartmentService(deps.db, a.base.baseBaseSysDepartmentModel, a.base.baseBaseSysUserModel, a.base.baseBaseSysUserRoleModel, a.base.baseBaseSysRoleDepartmentModel, deps.sessionStore, recycleManagerBaseNewDepartmentService)
	})
	return a.base.baseNewDepartmentService, a.base.baseNewDepartmentServiceErr
}

func (a *projectAssembly) getBaseNewMenuService(deps moduleDependencies) (*sys3.MenuService, error) {
	a.base.baseNewMenuServiceOnce.Do(func() {
		recycleManagerBaseNewMenuService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.base.baseNewMenuServiceErr = err
			return
		}
		a.base.baseNewMenuService = sys3.NewMenuService(deps.db, a.base.baseBaseSysMenuModel, a.base.baseBaseSysRoleModel, a.base.baseBaseSysRoleMenuModel, recycleManagerBaseNewMenuService)
	})
	return a.base.baseNewMenuService, a.base.baseNewMenuServiceErr
}

func (a *projectAssembly) getBaseNewParamService(deps moduleDependencies) (*sys3.ParamService, error) {
	a.base.baseNewParamServiceOnce.Do(func() {
		recycleManagerBaseNewParamService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.base.baseNewParamServiceErr = err
			return
		}
		a.base.baseNewParamService = sys3.NewParamService(deps.db, a.base.baseBaseSysParamModel, recycleManagerBaseNewParamService)
	})
	return a.base.baseNewParamService, a.base.baseNewParamServiceErr
}

func (a *projectAssembly) getBaseNewRoleService(deps moduleDependencies) (*sys3.RoleService, error) {
	a.base.baseNewRoleServiceOnce.Do(func() {
		recycleManagerBaseNewRoleService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.base.baseNewRoleServiceErr = err
			return
		}
		a.base.baseNewRoleService = sys3.NewRoleService(deps.db, a.base.baseBaseSysRoleModel, a.base.baseBaseSysUserRoleModel, a.base.baseBaseSysRoleMenuModel, a.base.baseBaseSysRoleDepartmentModel, deps.sessionStore, recycleManagerBaseNewRoleService)
	})
	return a.base.baseNewRoleService, a.base.baseNewRoleServiceErr
}

func (a *projectAssembly) getBaseNewUserService(deps moduleDependencies) (*sys3.UserService, error) {
	a.base.baseNewUserServiceOnce.Do(func() {
		recycleManagerBaseNewUserService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.base.baseNewUserServiceErr = err
			return
		}
		a.base.baseNewUserService = sys3.NewUserService(deps.db, a.base.baseBaseSysUserModel, a.base.baseBaseSysUserRoleModel, deps.sessionStore, recycleManagerBaseNewUserService)
	})
	return a.base.baseNewUserService, a.base.baseNewUserServiceErr
}

func (a *projectAssembly) getDictNewDictInfoService(deps moduleDependencies) (*service.DictInfoService, error) {
	a.dict.dictNewDictInfoServiceOnce.Do(func() {
		recycleManagerDictNewDictInfoService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.dict.dictNewDictInfoServiceErr = err
			return
		}
		a.dict.dictNewDictInfoService = service.NewDictInfoService(deps.db, a.dict.dictDictInfoModel, a.dict.dictDictTypeModel, recycleManagerDictNewDictInfoService)
	})
	return a.dict.dictNewDictInfoService, a.dict.dictNewDictInfoServiceErr
}

func (a *projectAssembly) getDictNewDictTypeService(deps moduleDependencies) (*service.DictTypeService, error) {
	a.dict.dictNewDictTypeServiceOnce.Do(func() {
		recycleManagerDictNewDictTypeService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.dict.dictNewDictTypeServiceErr = err
			return
		}
		a.dict.dictNewDictTypeService = service.NewDictTypeService(deps.db, a.dict.dictDictTypeModel, a.dict.dictDictInfoModel, recycleManagerDictNewDictTypeService)
	})
	return a.dict.dictNewDictTypeService, a.dict.dictNewDictTypeServiceErr
}

func (a *projectAssembly) getRecycleNewDataService(deps moduleDependencies) (*service2.DataService, error) {
	a.recycle.recycleNewDataServiceOnce.Do(func() {
		managerRecycleNewDataService, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.recycle.recycleNewDataServiceErr = err
			return
		}
		storeRecycleNewDataService, err := a.getRecycleNewStore(deps)
		if err != nil {
			a.recycle.recycleNewDataServiceErr = err
			return
		}
		catalogRecycleNewDataService, err := a.getRecycleNewCatalog(deps)
		if err != nil {
			a.recycle.recycleNewDataServiceErr = err
			return
		}
		a.recycle.recycleNewDataService, a.recycle.recycleNewDataServiceErr = service2.NewDataService(deps.db, managerRecycleNewDataService, storeRecycleNewDataService, a.recycle.recycleDataModel, catalogRecycleNewDataService, a.recycle.config)
	})
	return a.recycle.recycleNewDataService, a.recycle.recycleNewDataServiceErr
}

func (a *projectAssembly) getRecycleNewData(deps moduleDependencies) (*schedule.Data, error) {
	a.recycle.recycleNewDataOnce.Do(func() {
		serviceRecycleNewData, err := a.getRecycleNewDataService(deps)
		if err != nil {
			a.recycle.recycleNewDataErr = err
			return
		}
		a.recycle.recycleNewData = schedule.NewData(serviceRecycleNewData, a.recycle.config)
	})
	return a.recycle.recycleNewData, a.recycle.recycleNewDataErr
}

func (a *projectAssembly) getTaskNewRedisClient(deps moduleDependencies) (queue.RedisClient, error) {
	a.task.taskNewRedisClientOnce.Do(func() {
		a.task.taskNewRedisClient, a.task.taskNewRedisClientErr = queue.NewRedisClient(deps.redisDefault)
	})
	return a.task.taskNewRedisClient, a.task.taskNewRedisClientErr
}

func (a *projectAssembly) getTaskNewLocation(deps moduleDependencies) (*time.Location, error) {
	a.task.taskNewLocationOnce.Do(func() {
		a.task.taskNewLocation, a.task.taskNewLocationErr = service3.NewLocation(a.task.config)
	})
	return a.task.taskNewLocation, a.task.taskNewLocationErr
}

func (a *projectAssembly) getTaskNewComm(deps moduleDependencies) (*event3.Comm, error) {
	a.task.taskNewCommOnce.Do(func() {
		locationTaskNewComm, err := a.getTaskNewLocation(deps)
		if err != nil {
			a.task.taskNewCommErr = err
			return
		}
		redisClientTaskNewComm, err := a.getTaskNewRedisClient(deps)
		if err != nil {
			a.task.taskNewCommErr = err
			return
		}
		recycleManagerTaskNewComm, err := a.getRecycleNewManager(deps)
		if err != nil {
			a.task.taskNewCommErr = err
			return
		}
		a.task.taskNewComm, a.task.taskNewCommErr = event3.NewComm(deps.db, a.task.taskTaskInfoModel, a.task.taskTaskLogModel, deps.taskHandlers, a.task.config, locationTaskNewComm, redisClientTaskNewComm, recycleManagerTaskNewComm)
	})
	return a.task.taskNewComm, a.task.taskNewCommErr
}

func (a *projectAssembly) configureTaskHandlers(ctx context.Context) error {
	definition0 := service3.DemoDefinition()
	a.task.taskHandlers[0] = definition0
	return nil
}

// Specs 返回稳定排序且装配状态独立的模块声明。
func Specs() []module.Spec {
	assembly := &projectAssembly{}
	assembly.base.baseBaseSysConfModel = sys2.BaseSysConf()
	assembly.base.baseBaseSysDepartmentModel = sys2.BaseSysDepartment()
	assembly.base.baseBaseSysLogModel = sys2.BaseSysLog()
	assembly.base.baseBaseSysMenuModel = sys2.BaseSysMenu()
	assembly.base.baseBaseSysParamModel = sys2.BaseSysParam()
	assembly.base.baseBaseSysRoleModel = sys2.BaseSysRole()
	assembly.base.baseBaseSysRoleDepartmentModel = sys2.BaseSysRoleDepartment()
	assembly.base.baseBaseSysRoleMenuModel = sys2.BaseSysRoleMenu()
	assembly.base.baseBaseSysUserModel = sys2.BaseSysUser()
	assembly.base.baseBaseSysUserRoleModel = sys2.BaseSysUserRole()
	assembly.dict.dictDictInfoModel = entity2.DictInfo()
	assembly.dict.dictDictTypeModel = entity2.DictType()
	assembly.recycle.recycleDataModel = entity3.Data()
	assembly.recycle.recycleItemModel = entity3.Item()
	assembly.task.taskTaskInfoModel = entity4.TaskInfo()
	assembly.task.taskTaskLogModel = entity4.TaskLog()
	assembly.task.taskHandlers = make([]task.HandlerDefinition, 1)
	specs := make([]module.Spec, 0, 4)
	specRecycle := module.Spec{
		Key: "recycle", Name: "数据回收", Description: "收集被删除的数据，管理和恢复", Order: 0,
		Models: []entity.Definition{
			assembly.recycle.recycleDataModel,
			assembly.recycle.recycleItemModel,
		},
		Configure: func(ctx context.Context) error {
			if err := assembly.recycle.configure(ctx); err != nil {
				return err
			}
			return nil
		},
		DB: "modules/recycle/db.json",
	}
	specRecycle.RecycleProvider = func(source module.RuntimeDeps) (*recycle.Manager, module.Runtime, error) {
		deps := runtimeDependencies(source)
		manager, err := assembly.getRecycleNewManager(deps)
		if err != nil {
			return nil, nil, err
		}
		runtime0, err := assembly.getRecycleNewData(deps)
		if err != nil {
			return nil, nil, err
		}
		return manager, runtime0, nil
	}
	specRecycle.Controllers = func(source module.Deps) ([]controller.Definition, error) {
		deps := controllerDependencies(source)
		definitions := make([]controller.Definition, 0)
		serviceRecycleDataController, err := assembly.getRecycleNewDataService(deps)
		if err != nil {
			return nil, err
		}
		definition0 := admin3.DataController(serviceRecycleDataController, assembly.recycle.recycleDataModel)
		definitions = append(definitions, definition0)
		return definitions, nil
	}
	specs = append(specs, specRecycle)
	specBase := module.Spec{
		Key: "base", Name: "权限管理", Description: "基础的权限管理功能，包括登录，权限校验", Order: 10,
		Models: []entity.Definition{
			assembly.base.baseBaseSysConfModel,
			assembly.base.baseBaseSysDepartmentModel,
			assembly.base.baseBaseSysLogModel,
			assembly.base.baseBaseSysMenuModel,
			assembly.base.baseBaseSysParamModel,
			assembly.base.baseBaseSysRoleModel,
			assembly.base.baseBaseSysRoleDepartmentModel,
			assembly.base.baseBaseSysRoleMenuModel,
			assembly.base.baseBaseSysUserModel,
			assembly.base.baseBaseSysUserRoleModel,
		},
		Configure: func(ctx context.Context) error {
			if err := assembly.base.configure(ctx); err != nil {
				return err
			}
			return nil
		},
		DB:   "modules/base/db.json",
		Menu: "modules/base/menu.json",
	}
	specBase.Runtime = func(source module.RuntimeDeps) (module.Runtime, error) {
		deps := runtimeDependencies(source)
		runtime0, err := assembly.getBaseNewLog(deps)
		if err != nil {
			return nil, err
		}
		return runtime0, nil
	}
	specBase.Controllers = func(source module.Deps) ([]controller.Definition, error) {
		deps := controllerDependencies(source)
		definitions := make([]controller.Definition, 0)
		authServiceBaseBaseAdminOpenController, err := assembly.getBaseNewAuthService(deps)
		if err != nil {
			return nil, err
		}
		epsServiceBaseBaseAdminOpenController, err := assembly.getBaseNewEPSService(deps)
		if err != nil {
			return nil, err
		}
		definition0 := admin.BaseAdminOpenController(authServiceBaseBaseAdminOpenController, epsServiceBaseBaseAdminOpenController)
		definitions = append(definitions, definition0)
		logServiceBaseLogController, err := assembly.getBaseNewLogService(deps)
		if err != nil {
			return nil, err
		}
		confServiceBaseLogController, err := assembly.getBaseNewConfService(deps)
		if err != nil {
			return nil, err
		}
		definition1 := sys.LogController(logServiceBaseLogController, confServiceBaseLogController, assembly.base.baseBaseSysLogModel, assembly.base.baseBaseSysUserModel)
		definitions = append(definitions, definition1)
		departmentServiceBaseAdminDepartmentController, err := assembly.getBaseNewDepartmentService(deps)
		if err != nil {
			return nil, err
		}
		definition2 := sys.AdminDepartmentController(departmentServiceBaseAdminDepartmentController, assembly.base.baseBaseSysDepartmentModel)
		definitions = append(definitions, definition2)
		menuServiceBaseMenuController, err := assembly.getBaseNewMenuService(deps)
		if err != nil {
			return nil, err
		}
		definition3 := sys.MenuController(menuServiceBaseMenuController, assembly.base.baseBaseSysMenuModel)
		definitions = append(definitions, definition3)
		paramServiceBaseParamController, err := assembly.getBaseNewParamService(deps)
		if err != nil {
			return nil, err
		}
		definition4 := sys.ParamController(paramServiceBaseParamController, assembly.base.baseBaseSysParamModel)
		definitions = append(definitions, definition4)
		paramServiceBaseBaseAppCommController, err := assembly.getBaseNewParamService(deps)
		if err != nil {
			return nil, err
		}
		epsServiceBaseBaseAppCommController, err := assembly.getBaseNewEPSService(deps)
		if err != nil {
			return nil, err
		}
		uploadServiceBaseBaseAppCommController, err := assembly.getBaseNewService(deps)
		if err != nil {
			return nil, err
		}
		definition5 := app.BaseAppCommController(paramServiceBaseBaseAppCommController, epsServiceBaseBaseAppCommController, uploadServiceBaseBaseAppCommController, assembly.base.config)
		definitions = append(definitions, definition5)
		roleServiceBaseRoleController, err := assembly.getBaseNewRoleService(deps)
		if err != nil {
			return nil, err
		}
		definition6 := sys.RoleController(roleServiceBaseRoleController, assembly.base.baseBaseSysRoleModel)
		definitions = append(definitions, definition6)
		authServiceBaseBaseAdminCommController, err := assembly.getBaseNewAuthService(deps)
		if err != nil {
			return nil, err
		}
		userServiceBaseBaseAdminCommController, err := assembly.getBaseNewUserService(deps)
		if err != nil {
			return nil, err
		}
		permissionServiceBaseBaseAdminCommController, err := assembly.getBaseNewPermissionService(deps)
		if err != nil {
			return nil, err
		}
		uploadServiceBaseBaseAdminCommController, err := assembly.getBaseNewService(deps)
		if err != nil {
			return nil, err
		}
		definition7 := admin.BaseAdminCommController(authServiceBaseBaseAdminCommController, userServiceBaseBaseAdminCommController, permissionServiceBaseBaseAdminCommController, uploadServiceBaseBaseAdminCommController)
		definitions = append(definitions, definition7)
		userServiceBaseBaseAdminUserController, err := assembly.getBaseNewUserService(deps)
		if err != nil {
			return nil, err
		}
		definition8 := sys.BaseAdminUserController(userServiceBaseBaseAdminUserController, assembly.base.baseBaseSysUserModel)
		definitions = append(definitions, definition8)
		return definitions, nil
	}
	specBase.GlobalMiddlewares = func(source module.MiddlewareDeps) ([]middleware.Definition, error) {
		deps := middlewareDependencies(source)
		definitions := make([]middleware.Definition, 0)
		definition0, err := global.TranslateDefinition(deps.middlewareDeps, deps.i18nOptions)
		if err != nil {
			return nil, err
		}
		definitions = append(definitions, definition0)
		permissionServiceBaseAuthorityDefinitions, err := assembly.getBaseNewPermissionService(deps)
		if err != nil {
			return nil, err
		}
		definition1, err := global.AuthorityDefinitions(deps.middlewareDeps, assembly.base.config, deps.authOptions, permissionServiceBaseAuthorityDefinitions)
		if err != nil {
			return nil, err
		}
		definitions = append(definitions, definition1...)
		logRuntimeBaseLogDefinition, err := assembly.getBaseNewLog(deps)
		if err != nil {
			return nil, err
		}
		definition2, err := global.LogDefinition(assembly.base.config, logRuntimeBaseLogDefinition)
		if err != nil {
			return nil, err
		}
		definitions = append(definitions, definition2...)
		return definitions, nil
	}
	specs = append(specs, specBase)
	specDict := module.Spec{
		Key: "dict", Name: "字典管理", Description: "数据字典等", Order: 0,
		Models: []entity.Definition{
			assembly.dict.dictDictInfoModel,
			assembly.dict.dictDictTypeModel,
		},
		Configure: func(ctx context.Context) error {
			if err := assembly.dict.configure(ctx); err != nil {
				return err
			}
			return nil
		},
		DB: "modules/dict/db.json",
	}
	specDict.Controllers = func(source module.Deps) ([]controller.Definition, error) {
		deps := controllerDependencies(source)
		definitions := make([]controller.Definition, 0)
		infoServiceDictInfoController, err := assembly.getDictNewDictInfoService(deps)
		if err != nil {
			return nil, err
		}
		definition0 := admin2.InfoController(infoServiceDictInfoController, assembly.dict.dictDictInfoModel)
		definitions = append(definitions, definition0)
		typeServiceDictTypeController, err := assembly.getDictNewDictTypeService(deps)
		if err != nil {
			return nil, err
		}
		definition1 := admin2.TypeController(typeServiceDictTypeController, assembly.dict.dictDictTypeModel)
		definitions = append(definitions, definition1)
		return definitions, nil
	}
	specs = append(specs, specDict)
	specTask := module.Spec{
		Key: "task", Name: "任务调度", Description: "任务调度模块，支持分布式任务，由redis整个集群的任务", Order: 0,
		Models: []entity.Definition{
			assembly.task.taskTaskInfoModel,
			assembly.task.taskTaskLogModel,
		},
		Configure: func(ctx context.Context) error {
			if err := assembly.task.configure(ctx); err != nil {
				return err
			}
			return assembly.configureTaskHandlers(ctx)
		},
		TaskHandlers: assembly.task.taskHandlers,
		DB:           "modules/task/db.json",
	}
	specTask.Runtime = func(source module.RuntimeDeps) (module.Runtime, error) {
		deps := runtimeDependencies(source)
		runtime0, err := assembly.getTaskNewComm(deps)
		if err != nil {
			return nil, err
		}
		return runtime0, nil
	}
	specTask.Controllers = func(source module.Deps) ([]controller.Definition, error) {
		deps := controllerDependencies(source)
		definitions := make([]controller.Definition, 0)
		commTaskInfoController, err := assembly.getTaskNewComm(deps)
		if err != nil {
			return nil, err
		}
		definition0 := admin4.InfoController(commTaskInfoController, assembly.task.taskTaskInfoModel)
		definitions = append(definitions, definition0)
		return definitions, nil
	}
	specTask.Middlewares = func(source module.MiddlewareDeps) ([]middleware.Definition, error) {
		deps := middlewareDependencies(source)
		definitions := make([]middleware.Definition, 0)
		commTaskDefinition, err := assembly.getTaskNewComm(deps)
		if err != nil {
			return nil, err
		}
		definition0 := middleware2.Definition(commTaskDefinition)
		definitions = append(definitions, definition0)
		return definitions, nil
	}
	specs = append(specs, specTask)
	return specs
}
